[package]
name = "astal-river"
authors.workspace = true
categories.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true
readme.workspace = true
edition.workspace = true

[dependencies]
astal-river-sys = { version = "0.1.0", path = "sys" }
glib.workspace = true

[features]
gio_v2_22 = []
