// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../../girs
// from ../../gtk-girs
// DO NOT EDIT

#include "manual.h"
#include <stdio.h>

#define PRINT_CONSTANT(CONSTANT_NAME) \
    printf("%s;", #CONSTANT_NAME); \
    printf(_Generic((CONSTANT_NAME), \
                    char *: "%s", \
                    const char *: "%s", \
                    char: "%c", \
                    signed char: "%hhd", \
                    unsigned char: "%hhu", \
                    short int: "%hd", \
                    unsigned short int: "%hu", \
                    int: "%d", \
                    unsigned int: "%u", \
                    long: "%ld", \
                    unsigned long: "%lu", \
                    long long: "%lld", \
                    unsigned long long: "%llu", \
                    float: "%f", \
                    double: "%f", \
                    long double: "%ld"), \
           CONSTANT_NAME); \
    printf("\n");

int main() {
    PRINT_CONSTANT((gint) ASTAL_NETWORK_CONNECTIVITY_FULL);
    PRINT_CONSTANT((gint) ASTAL_NETWORK_CONNECTIVITY_LIMITED);
    PRINT_CONSTANT((gint) ASTAL_NETWORK_CONNECTIVITY_NONE);
    PRINT_CONSTANT((gint) ASTAL_NETWORK_CONNECTIVITY_PORTAL);
    PRINT_CONSTANT((gint) ASTAL_NETWORK_CONNECTIVITY_UNKNOWN);
    PRINT_CONSTANT((gint) ASTAL_NETWORK_DEVICE_STATE_ACTIVATED);
    PRINT_CONSTANT((gint) ASTAL_NETWORK_DEVICE_STATE_CONFIG);
    PRINT_CONSTANT((gint) ASTAL_NETWORK_DEVICE_STATE_DEACTIVATING);
    PRINT_CONSTANT((gint) ASTAL_NETWORK_DEVICE_STATE_DISCONNECTED);
    PRINT_CONSTANT((gint) ASTAL_NETWORK_DEVICE_STATE_FAILED);
    PRINT_CONSTANT((gint) ASTAL_NETWORK_DEVICE_STATE_IP_CHECK);
    PRINT_CONSTANT((gint) ASTAL_NETWORK_DEVICE_STATE_IP_CONFIG);
    PRINT_CONSTANT((gint) ASTAL_NETWORK_DEVICE_STATE_NEED_AUTH);
    PRINT_CONSTANT((gint) ASTAL_NETWORK_DEVICE_STATE_PREPARE);
    PRINT_CONSTANT((gint) ASTAL_NETWORK_DEVICE_STATE_SECONDARIES);
    PRINT_CONSTANT((gint) ASTAL_NETWORK_DEVICE_STATE_UNAVAILABLE);
    PRINT_CONSTANT((gint) ASTAL_NETWORK_DEVICE_STATE_UNKNOWN);
    PRINT_CONSTANT((gint) ASTAL_NETWORK_DEVICE_STATE_UNMANAGED);
    PRINT_CONSTANT((gint) ASTAL_NETWORK_INTERNET_CONNECTED);
    PRINT_CONSTANT((gint) ASTAL_NETWORK_INTERNET_CONNECTING);
    PRINT_CONSTANT((gint) ASTAL_NETWORK_INTERNET_DISCONNECTED);
    PRINT_CONSTANT(ASTAL_NETWORK_MAJOR_VERSION);
    PRINT_CONSTANT(ASTAL_NETWORK_MICRO_VERSION);
    PRINT_CONSTANT(ASTAL_NETWORK_MINOR_VERSION);
    PRINT_CONSTANT((gint) ASTAL_NETWORK_PRIMARY_UNKNOWN);
    PRINT_CONSTANT((gint) ASTAL_NETWORK_PRIMARY_WIFI);
    PRINT_CONSTANT((gint) ASTAL_NETWORK_PRIMARY_WIRED);
    PRINT_CONSTANT((gint) ASTAL_NETWORK_STATE_ASLEEP);
    PRINT_CONSTANT((gint) ASTAL_NETWORK_STATE_CONNECTED_GLOBAL);
    PRINT_CONSTANT((gint) ASTAL_NETWORK_STATE_CONNECTED_LOCAL);
    PRINT_CONSTANT((gint) ASTAL_NETWORK_STATE_CONNECTED_SITE);
    PRINT_CONSTANT((gint) ASTAL_NETWORK_STATE_CONNECTING);
    PRINT_CONSTANT((gint) ASTAL_NETWORK_STATE_DISCONNECTED);
    PRINT_CONSTANT((gint) ASTAL_NETWORK_STATE_DISCONNECTING);
    PRINT_CONSTANT((gint) ASTAL_NETWORK_STATE_UNKNOWN);
    PRINT_CONSTANT(ASTAL_NETWORK_VERSION);
    return 0;
}
