[options]
girs_directories = ["../../gtk-girs", "../../girs"]
library = "AstalMpris"
version = "0.1"
min_cfg_version = "0.1"
target_path = "."
work_mode = "normal"
use_gi_docgen = true
generate_safety_asserts = true
deprecate_by_min_version = true
single_version_file = true
generate_builder = true
trust_return_value_nullability = true

generate = [
    "AstalMpris.PlaybackStatus",
    "AstalMpris.Loop",
    "AstalMpris.Shuffle",
    "AstalMpris.Mpris",
    "AstalMpris.Player",
]

manual = ["GLib.Variant", "Gio.ListModel"]

[[object]]
name = "AstalMpris.*"
status = "generate"
