[options]
library = "Astal"
version = "4.0"
target_path = "."
girs_directories = ["../../gtk-girs/", "../../girs/"]
work_mode = "sys"
single_version_file = true
min_cfg_version = "4.0"

external_libraries = ["GLib", "GObject", "Gtk4", "Gio", "Gdk"]
