[package]
name = "astal-io"
authors.workspace = true
categories.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true
readme.workspace = true

[dependencies]
astal-io-sys = { version = "0.1.0", path = "sys" }
gio.workspace = true
glib.workspace = true

[features]
gio_v2_80 = ["gio/v2_80"]
gio_v2_28 = []
gio_v2_32 = []
