[options]
girs_directories = ["../../gtk-girs", "../../girs"]
library = "AstalIO"
version = "0.1"
min_cfg_version = "0.1"
target_path = "."
work_mode = "normal"
use_gi_docgen = true
generate_safety_asserts = true
deprecate_by_min_version = true
single_version_file = true
generate_builder = true
trust_return_value_nullability = true

generate = [
    "AstalIO.AppError",
    "AstalIO.Application",
    "AstalIO.Daemon",
    "AstalIO.Process",
    "AstalIO.Time",
    "AstalIO.VariableBase",
    "AstalIO.Variable",
]

manual = [
    "GLib.Error",
    "Gio.SocketConnection",
    "Gio.Application",
    "Gio.ActionGroup",
    "Gio.ActionMap",
    "Gio.AsyncReadyCallback",
    "Gio.AsyncResult",
    "GObject.Closure",
    "GObject.Value",
    "Gio.SocketService",
    "Gio.FileMonitor",
]

[[object]]
name = "AstalIO.*"
status = "generate"
