// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../girs
// from ../gtk-girs
// DO NOT EDIT

mod application;
pub use self::application::Application;

mod bin;
pub use self::bin::Bin;

#[deprecated = "Since 0"]
mod box_;
#[deprecated = "Since 0"]
pub use self::box_::Box;

mod slider;
pub use self::slider::Slider;

mod window;
pub use self::window::Window;

mod enums;
pub use self::enums::Exclusivity;
pub use self::enums::Keymode;
pub use self::enums::Layer;

mod flags;
pub use self::flags::WindowAnchor;

mod constants;
pub use self::constants::VERSION;

pub(crate) mod traits {
    pub use super::application::ApplicationExt;
    pub use super::bin::BinExt;
    #[deprecated = "Since 0"]
    pub use super::box_::BoxExt;
    pub use super::slider::SliderExt;
    pub use super::window::WindowExt;
}
pub(crate) mod builders {
    pub use super::application::ApplicationBuilder;
    pub use super::bin::BinBuilder;
    #[deprecated = "Since 0"]
    pub use super::box_::BoxBuilder;
    pub use super::slider::SliderBuilder;
    pub use super::window::WindowBuilder;
}
