// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../girs
// from ../gtk-girs
// DO NOT EDIT

use crate::{Exclusivity, Keymode, Layer, WindowAnchor, ffi};
use crate::{gobject, gtk, prelude::IsA};
use glib::object::Cast;
use glib::translate::ToGlibPtr as GlibToGlibPtr;
use glib::{
    signal::{SignalHandlerId, connect_raw},
    translate::*,
};
use gtk4::gdk;
use std::boxed::Box as Box_;

glib::wrapper! {
    /// Subclass of [`gtk::Window`][crate::gtk::Window] which integrates GtkLayerShell as class fields.
    ///
    /// ## Properties
    ///
    ///
    /// #### `namespace`
    ///  Namespace of this window. This can be used to target the layer in compositor rules.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `anchor`
    ///  Edges to anchor the window to.
    /// If two perpendicular edges are anchored, the surface will be anchored to that corner. If two opposite edges are anchored, the window will be
    /// stretched across the screen in that direction.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `exclusivity`
    ///  Exclusivity of this window.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `layer`
    ///  Which layer to appear this window on.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `keymode`
    ///  Keyboard mode of this window.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `gdkmonitor`
    ///  Which monitor to appear this window on.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `margin-top`
    ///  Readable | Writeable
    ///
    ///
    /// #### `margin-bottom`
    ///  Readable | Writeable
    ///
    ///
    /// #### `margin-left`
    ///  Readable | Writeable
    ///
    ///
    /// #### `margin-right`
    ///  Readable | Writeable
    ///
    ///
    /// #### `margin`
    ///  Writeable
    ///
    ///
    /// #### `monitor`
    ///  Which monitor to appear this window on.
    /// CAUTION: the id might not be the same mapped by the compositor.
    ///
    /// Readable | Writeable
    /// <details><summary><h4>Window</h4></summary>
    ///
    ///
    /// #### `application`
    ///  The [`gtk::Application`][crate::gtk::Application] associated with the window.
    ///
    /// The application will be kept alive for at least as long as it
    /// has any windows associated with it (see g_application_hold()
    /// for a way to keep it alive without windows).
    ///
    /// Normally, the connection between the application and the window
    /// will remain until the window is destroyed, but you can explicitly
    /// remove it by setting the this property to `NULL`.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `child`
    ///  The child widget.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `decorated`
    ///  Whether the window should have a frame (also known as *decorations*).
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `default-height`
    ///  The default height of the window.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `default-widget`
    ///  The default widget.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `default-width`
    ///  The default width of the window.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `deletable`
    ///  Whether the window frame should have a close button.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `destroy-with-parent`
    ///  If this window should be destroyed when the parent is destroyed.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `display`
    ///  The display that will display this window.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `focus-visible`
    ///  Whether 'focus rectangles' are currently visible in this window.
    ///
    /// This property is maintained by GTK based on user input
    /// and should not be set by applications.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `focus-widget`
    ///  The focus widget.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `fullscreened`
    ///  Whether the window is fullscreen.
    ///
    /// Setting this property is the equivalent of calling
    /// [`WindowExtManual::fullscreen()`][crate::gtk::prelude::WindowExtManual::fullscreen()] or [`WindowExtManual::unfullscreen()`][crate::gtk::prelude::WindowExtManual::unfullscreen()];
    /// either operation is asynchronous, which means you will need to
    /// connect to the ::notify signal in order to know whether the
    /// operation was successful.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `gravity`
    ///  The gravity to use when resizing the window programmatically.
    ///
    /// Gravity describes which point of the window we want to keep
    /// fixed (meaning that the window will grow in the opposite direction).
    /// For example, a gravity of `GTK_WINDOW_GRAVITY_TOP_RIGHT` means that we
    /// want the to fix top right corner of the window.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `handle-menubar-accel`
    ///  Whether the window frame should handle <kbd>F10</kbd> for activating
    /// menubars.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `hide-on-close`
    ///  If this window should be hidden instead of destroyed when the user clicks
    /// the close button.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `icon-name`
    ///  Specifies the name of the themed icon to use as the window icon.
    ///
    /// See `Gtk::IconTheme` for more details.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `is-active`
    ///  Whether the toplevel is the currently active window.
    ///
    /// Readable
    ///
    ///
    /// #### `maximized`
    ///  Whether the window is maximized.
    ///
    /// Setting this property is the equivalent of calling
    /// [`WindowExtManual::maximize()`][crate::gtk::prelude::WindowExtManual::maximize()] or [`WindowExtManual::unmaximize()`][crate::gtk::prelude::WindowExtManual::unmaximize()];
    /// either operation is asynchronous, which means you will need to
    /// connect to the ::notify signal in order to know whether the
    /// operation was successful.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `mnemonics-visible`
    ///  Whether mnemonics are currently visible in this window.
    ///
    /// This property is maintained by GTK based on user input,
    /// and should not be set by applications.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `modal`
    ///  If true, the window is modal.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `resizable`
    ///  If true, users can resize the window.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `startup-id`
    ///  A write-only property for setting window's startup notification identifier.
    ///
    /// Writeable
    ///
    ///
    /// #### `suspended`
    ///  Whether the window is suspended.
    ///
    /// See [`WindowExtManual::is_suspended()`][crate::gtk::prelude::WindowExtManual::is_suspended()] for details about what suspended means.
    ///
    /// Readable
    ///
    ///
    /// #### `title`
    ///  The title of the window.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `titlebar`
    ///  The titlebar widget.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `transient-for`
    ///  The transient parent of the window.
    ///
    /// Readable | Writeable | Construct
    /// </details>
    /// <details><summary><h4>Widget</h4></summary>
    ///
    ///
    /// #### `can-focus`
    ///  Whether the widget or any of its descendents can accept
    /// the input focus.
    ///
    /// This property is meant to be set by widget implementations,
    /// typically in their instance init function.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `can-target`
    ///  Whether the widget can receive pointer events.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `css-classes`
    ///  A list of css classes applied to this widget.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `css-name`
    ///  The name of this widget in the CSS tree.
    ///
    /// This property is meant to be set by widget implementations,
    /// typically in their instance init function.
    ///
    /// Readable | Writeable | Construct Only
    ///
    ///
    /// #### `cursor`
    ///  The cursor used by @widget.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `focus-on-click`
    ///  Whether the widget should grab focus when it is clicked with the mouse.
    ///
    /// This property is only relevant for widgets that can take focus.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `focusable`
    ///  Whether this widget itself will accept the input focus.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `halign`
    ///  How to distribute horizontal space if widget gets extra space.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `has-default`
    ///  Whether the widget is the default widget.
    ///
    /// Readable
    ///
    ///
    /// #### `has-focus`
    ///  Whether the widget has the input focus.
    ///
    /// Readable
    ///
    ///
    /// #### `has-tooltip`
    ///  Enables or disables the emission of the [`query-tooltip`][struct@crate::gtk::Widget#query-tooltip]
    /// signal on @widget.
    ///
    /// A true value indicates that @widget can have a tooltip, in this case
    /// the widget will be queried using [`query-tooltip`][struct@crate::gtk::Widget#query-tooltip] to
    /// determine whether it will provide a tooltip or not.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `height-request`
    ///  Overrides for height request of the widget.
    ///
    /// If this is -1, the natural request will be used.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `hexpand`
    ///  Whether to expand horizontally.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `hexpand-set`
    ///  Whether to use the `hexpand` property.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `layout-manager`
    ///  The `Gtk::LayoutManager` instance to use to compute
    /// the preferred size of the widget, and allocate its children.
    ///
    /// This property is meant to be set by widget implementations,
    /// typically in their instance init function.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `limit-events`
    ///  Makes this widget act like a modal dialog, with respect to
    /// event delivery.
    ///
    /// Global event controllers will not handle events with targets
    /// inside the widget, unless they are set up to ignore propagation
    /// limits. See `Gtk::EventController::set_propagation_limit()`.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `margin-bottom`
    ///  Margin on bottom side of widget.
    ///
    /// This property adds margin outside of the widget's normal size
    /// request, the margin will be added in addition to the size from
    /// [`WidgetExtManual::set_size_request()`][crate::gtk::prelude::WidgetExtManual::set_size_request()] for example.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `margin-end`
    ///  Margin on end of widget, horizontally.
    ///
    /// This property supports left-to-right and right-to-left text
    /// directions.
    ///
    /// This property adds margin outside of the widget's normal size
    /// request, the margin will be added in addition to the size from
    /// [`WidgetExtManual::set_size_request()`][crate::gtk::prelude::WidgetExtManual::set_size_request()] for example.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `margin-start`
    ///  Margin on start of widget, horizontally.
    ///
    /// This property supports left-to-right and right-to-left text
    /// directions.
    ///
    /// This property adds margin outside of the widget's normal size
    /// request, the margin will be added in addition to the size from
    /// [`WidgetExtManual::set_size_request()`][crate::gtk::prelude::WidgetExtManual::set_size_request()] for example.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `margin-top`
    ///  Margin on top side of widget.
    ///
    /// This property adds margin outside of the widget's normal size
    /// request, the margin will be added in addition to the size from
    /// [`WidgetExtManual::set_size_request()`][crate::gtk::prelude::WidgetExtManual::set_size_request()] for example.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `name`
    ///  The name of the widget.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `opacity`
    ///  The requested opacity of the widget.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `overflow`
    ///  How content outside the widget's content area is treated.
    ///
    /// This property is meant to be set by widget implementations,
    /// typically in their instance init function.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `parent`
    ///  The parent widget of this widget.
    ///
    /// Readable
    ///
    ///
    /// #### `receives-default`
    ///  Whether the widget will receive the default action when it is focused.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `root`
    ///  The [`gtk::Root`][crate::gtk::Root] widget of the widget tree containing this widget.
    ///
    /// This will be `NULL` if the widget is not contained in a root widget.
    ///
    /// Readable
    ///
    ///
    /// #### `scale-factor`
    ///  The scale factor of the widget.
    ///
    /// Readable
    ///
    ///
    /// #### `sensitive`
    ///  Whether the widget responds to input.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `tooltip-markup`
    ///  Sets the text of tooltip to be the given string, which is marked up
    /// with Pango markup.
    ///
    /// Also see `Gtk::Tooltip::set_markup()`.
    ///
    /// This is a convenience property which will take care of getting the
    /// tooltip shown if the given string is not `NULL`:
    /// [`has-tooltip`][struct@crate::gtk::Widget#has-tooltip] will automatically be set to true
    /// and there will be taken care of [`query-tooltip`][struct@crate::gtk::Widget#query-tooltip] in
    /// the default signal handler.
    ///
    /// Note that if both [`tooltip-text`][struct@crate::gtk::Widget#tooltip-text] and
    /// [`tooltip-markup`][struct@crate::gtk::Widget#tooltip-markup] are set, the last one wins.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `tooltip-text`
    ///  Sets the text of tooltip to be the given string.
    ///
    /// Also see `Gtk::Tooltip::set_text()`.
    ///
    /// This is a convenience property which will take care of getting the
    /// tooltip shown if the given string is not `NULL`:
    /// [`has-tooltip`][struct@crate::gtk::Widget#has-tooltip] will automatically be set to true
    /// and there will be taken care of [`query-tooltip`][struct@crate::gtk::Widget#query-tooltip] in
    /// the default signal handler.
    ///
    /// Note that if both [`tooltip-text`][struct@crate::gtk::Widget#tooltip-text] and
    /// [`tooltip-markup`][struct@crate::gtk::Widget#tooltip-markup] are set, the last one wins.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `valign`
    ///  How to distribute vertical space if widget gets extra space.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `vexpand`
    ///  Whether to expand vertically.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `vexpand-set`
    ///  Whether to use the `vexpand` property.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `visible`
    ///  Whether the widget is visible.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `width-request`
    ///  Overrides for width request of the widget.
    ///
    /// If this is -1, the natural request will be used.
    ///
    /// Readable | Writeable
    /// </details>
    /// <details><summary><h4>Accessible</h4></summary>
    ///
    ///
    /// #### `accessible-role`
    ///  The accessible role of the given [`gtk::Accessible`][crate::gtk::Accessible] implementation.
    ///
    /// The accessible role cannot be changed once set.
    ///
    /// Readable | Writeable
    /// </details>
    ///
    /// # Implements
    ///
    /// [`WindowExt`][trait@crate::prelude::WindowExt], [`trait@gtk::prelude::WindowExt`], [`trait@gtk::prelude::WidgetExt`], [`trait@glib::InitiallyUnownedExt`], [`trait@gtk::prelude::AccessibleExt`], [`trait@gtk::prelude::BuildableExt`], [`trait@gtk::prelude::ConstraintTargetExt`], [`trait@gtk::prelude::NativeExt`], [`trait@gtk::prelude::RootExt`], [`trait@gtk::prelude::ShortcutManagerExt`]
    #[doc(alias = "AstalWindow")]
    pub struct Window(Object<ffi::AstalWindow, ffi::AstalWindowClass>) @extends gtk::Window, gtk::Widget, gobject::InitiallyUnowned, @implements gtk::Accessible, gtk::Buildable, gtk::ConstraintTarget, gtk::Native, gtk::Root, gtk::ShortcutManager;

    match fn {
        type_ => || ffi::astal_window_get_type(),
    }
}

impl Window {
    pub const NONE: Option<&'static Window> = None;

    #[doc(alias = "astal_window_new")]
    pub fn new() -> Window {
        assert_initialized_main_thread!();
        unsafe { from_glib_none(ffi::astal_window_new()) }
    }

    // rustdoc-stripper-ignore-next
    /// Creates a new builder-pattern struct instance to construct [`Window`] objects.
    ///
    /// This method returns an instance of [`WindowBuilder`](crate::builders::WindowBuilder) which can be used to create [`Window`] objects.
    pub fn builder() -> WindowBuilder {
        WindowBuilder::new()
    }
}

impl Default for Window {
    fn default() -> Self {
        Self::new()
    }
}

// rustdoc-stripper-ignore-next
/// A [builder-pattern] type to construct [`Window`] objects.
///
/// [builder-pattern]: https://doc.rust-lang.org/1.0.0/style/ownership/builders.html
#[must_use = "The builder must be built to be used"]
pub struct WindowBuilder {
    builder: glib::object::ObjectBuilder<'static, Window>,
}

impl WindowBuilder {
    fn new() -> Self {
        Self {
            builder: glib::object::Object::builder(),
        }
    }

    /// Namespace of this window. This can be used to target the layer in compositor rules.
    pub fn namespace(self, namespace: impl Into<glib::GString>) -> Self {
        Self {
            builder: self.builder.property("namespace", namespace.into()),
        }
    }

    /// Edges to anchor the window to.
    /// If two perpendicular edges are anchored, the surface will be anchored to that corner. If two opposite edges are anchored, the window will be
    /// stretched across the screen in that direction.
    pub fn anchor(self, anchor: WindowAnchor) -> Self {
        Self {
            builder: self.builder.property("anchor", anchor),
        }
    }

    /// Exclusivity of this window.
    pub fn exclusivity(self, exclusivity: Exclusivity) -> Self {
        Self {
            builder: self.builder.property("exclusivity", exclusivity),
        }
    }

    /// Which layer to appear this window on.
    pub fn layer(self, layer: Layer) -> Self {
        Self {
            builder: self.builder.property("layer", layer),
        }
    }

    /// Keyboard mode of this window.
    pub fn keymode(self, keymode: Keymode) -> Self {
        Self {
            builder: self.builder.property("keymode", keymode),
        }
    }

    /// Which monitor to appear this window on.
    pub fn gdkmonitor(self, gdkmonitor: &gdk::Monitor) -> Self {
        Self {
            builder: self.builder.property("gdkmonitor", gdkmonitor.clone()),
        }
    }

    /// Margin on top side of widget.
    ///
    /// This property adds margin outside of the widget's normal size
    /// request, the margin will be added in addition to the size from
    /// [`WidgetExtManual::set_size_request()`][crate::gtk::prelude::WidgetExtManual::set_size_request()] for example.
    pub fn margin_top(self, margin_top: i32) -> Self {
        Self {
            builder: self.builder.property("margin-top", margin_top),
        }
    }

    /// Margin on bottom side of widget.
    ///
    /// This property adds margin outside of the widget's normal size
    /// request, the margin will be added in addition to the size from
    /// [`WidgetExtManual::set_size_request()`][crate::gtk::prelude::WidgetExtManual::set_size_request()] for example.
    pub fn margin_bottom(self, margin_bottom: i32) -> Self {
        Self {
            builder: self.builder.property("margin-bottom", margin_bottom),
        }
    }

    pub fn margin_left(self, margin_left: i32) -> Self {
        Self {
            builder: self.builder.property("margin-left", margin_left),
        }
    }

    pub fn margin_right(self, margin_right: i32) -> Self {
        Self {
            builder: self.builder.property("margin-right", margin_right),
        }
    }

    pub fn margin(self, margin: i32) -> Self {
        Self {
            builder: self.builder.property("margin", margin),
        }
    }

    /// Which monitor to appear this window on.
    /// CAUTION: the id might not be the same mapped by the compositor.
    pub fn monitor(self, monitor: i32) -> Self {
        Self {
            builder: self.builder.property("monitor", monitor),
        }
    }

    /// The [`gtk::Application`][crate::gtk::Application] associated with the window.
    ///
    /// The application will be kept alive for at least as long as it
    /// has any windows associated with it (see g_application_hold()
    /// for a way to keep it alive without windows).
    ///
    /// Normally, the connection between the application and the window
    /// will remain until the window is destroyed, but you can explicitly
    /// remove it by setting the this property to `NULL`.
    pub fn application(self, application: &impl IsA<gtk::Application>) -> Self {
        Self {
            builder: self
                .builder
                .property("application", application.clone().upcast()),
        }
    }

    /// The child widget.
    pub fn child(self, child: &impl IsA<gtk::Widget>) -> Self {
        Self {
            builder: self.builder.property("child", child.clone().upcast()),
        }
    }

    /// Whether the window should have a frame (also known as *decorations*).
    pub fn decorated(self, decorated: bool) -> Self {
        Self {
            builder: self.builder.property("decorated", decorated),
        }
    }

    /// The default height of the window.
    pub fn default_height(self, default_height: i32) -> Self {
        Self {
            builder: self.builder.property("default-height", default_height),
        }
    }

    /// The default widget.
    pub fn default_widget(self, default_widget: &impl IsA<gtk::Widget>) -> Self {
        Self {
            builder: self
                .builder
                .property("default-widget", default_widget.clone().upcast()),
        }
    }

    /// The default width of the window.
    pub fn default_width(self, default_width: i32) -> Self {
        Self {
            builder: self.builder.property("default-width", default_width),
        }
    }

    /// Whether the window frame should have a close button.
    pub fn deletable(self, deletable: bool) -> Self {
        Self {
            builder: self.builder.property("deletable", deletable),
        }
    }

    /// If this window should be destroyed when the parent is destroyed.
    pub fn destroy_with_parent(self, destroy_with_parent: bool) -> Self {
        Self {
            builder: self
                .builder
                .property("destroy-with-parent", destroy_with_parent),
        }
    }

    //pub fn display(self, display: /*Ignored*/&gdk::Display) -> Self {
    //    Self { builder: self.builder.property("display", display), }
    //}

    /// Whether 'focus rectangles' are currently visible in this window.
    ///
    /// This property is maintained by GTK based on user input
    /// and should not be set by applications.
    pub fn focus_visible(self, focus_visible: bool) -> Self {
        Self {
            builder: self.builder.property("focus-visible", focus_visible),
        }
    }

    /// The focus widget.
    pub fn focus_widget(self, focus_widget: &impl IsA<gtk::Widget>) -> Self {
        Self {
            builder: self
                .builder
                .property("focus-widget", focus_widget.clone().upcast()),
        }
    }

    /// Whether the window is fullscreen.
    ///
    /// Setting this property is the equivalent of calling
    /// [`WindowExtManual::fullscreen()`][crate::gtk::prelude::WindowExtManual::fullscreen()] or [`WindowExtManual::unfullscreen()`][crate::gtk::prelude::WindowExtManual::unfullscreen()];
    /// either operation is asynchronous, which means you will need to
    /// connect to the ::notify signal in order to know whether the
    /// operation was successful.
    pub fn fullscreened(self, fullscreened: bool) -> Self {
        Self {
            builder: self.builder.property("fullscreened", fullscreened),
        }
    }

    //    #[cfg(feature = "gtk_v4_20")]
    #[cfg_attr(docsrs, doc(cfg(feature = "gtk_v4_20")))]
    //pub fn gravity(self, gravity: /*Ignored*/gtk::WindowGravity) -> Self {
    //    Self { builder: self.builder.property("gravity", gravity), }
    //}
    /// Whether the window frame should handle <kbd>F10</kbd> for activating
    /// menubars.
    #[cfg(feature = "gtk_v4_2")]
    #[cfg_attr(docsrs, doc(cfg(feature = "gtk_v4_2")))]
    pub fn handle_menubar_accel(self, handle_menubar_accel: bool) -> Self {
        Self {
            builder: self
                .builder
                .property("handle-menubar-accel", handle_menubar_accel),
        }
    }

    /// If this window should be hidden instead of destroyed when the user clicks
    /// the close button.
    pub fn hide_on_close(self, hide_on_close: bool) -> Self {
        Self {
            builder: self.builder.property("hide-on-close", hide_on_close),
        }
    }

    /// Specifies the name of the themed icon to use as the window icon.
    ///
    /// See `Gtk::IconTheme` for more details.
    pub fn icon_name(self, icon_name: impl Into<glib::GString>) -> Self {
        Self {
            builder: self.builder.property("icon-name", icon_name.into()),
        }
    }

    /// Whether the window is maximized.
    ///
    /// Setting this property is the equivalent of calling
    /// [`WindowExtManual::maximize()`][crate::gtk::prelude::WindowExtManual::maximize()] or [`WindowExtManual::unmaximize()`][crate::gtk::prelude::WindowExtManual::unmaximize()];
    /// either operation is asynchronous, which means you will need to
    /// connect to the ::notify signal in order to know whether the
    /// operation was successful.
    pub fn maximized(self, maximized: bool) -> Self {
        Self {
            builder: self.builder.property("maximized", maximized),
        }
    }

    /// Whether mnemonics are currently visible in this window.
    ///
    /// This property is maintained by GTK based on user input,
    /// and should not be set by applications.
    pub fn mnemonics_visible(self, mnemonics_visible: bool) -> Self {
        Self {
            builder: self
                .builder
                .property("mnemonics-visible", mnemonics_visible),
        }
    }

    /// If true, the window is modal.
    pub fn modal(self, modal: bool) -> Self {
        Self {
            builder: self.builder.property("modal", modal),
        }
    }

    /// If true, users can resize the window.
    pub fn resizable(self, resizable: bool) -> Self {
        Self {
            builder: self.builder.property("resizable", resizable),
        }
    }

    /// A write-only property for setting window's startup notification identifier.
    pub fn startup_id(self, startup_id: impl Into<glib::GString>) -> Self {
        Self {
            builder: self.builder.property("startup-id", startup_id.into()),
        }
    }

    /// The title of the window.
    pub fn title(self, title: impl Into<glib::GString>) -> Self {
        Self {
            builder: self.builder.property("title", title.into()),
        }
    }

    /// The titlebar widget.
    #[cfg(feature = "gtk_v4_6")]
    #[cfg_attr(docsrs, doc(cfg(feature = "gtk_v4_6")))]
    pub fn titlebar(self, titlebar: &impl IsA<gtk::Widget>) -> Self {
        Self {
            builder: self.builder.property("titlebar", titlebar.clone().upcast()),
        }
    }

    /// The transient parent of the window.
    pub fn transient_for(self, transient_for: &impl IsA<gtk::Window>) -> Self {
        Self {
            builder: self
                .builder
                .property("transient-for", transient_for.clone().upcast()),
        }
    }

    /// Whether the widget or any of its descendents can accept
    /// the input focus.
    ///
    /// This property is meant to be set by widget implementations,
    /// typically in their instance init function.
    pub fn can_focus(self, can_focus: bool) -> Self {
        Self {
            builder: self.builder.property("can-focus", can_focus),
        }
    }

    /// Whether the widget can receive pointer events.
    pub fn can_target(self, can_target: bool) -> Self {
        Self {
            builder: self.builder.property("can-target", can_target),
        }
    }

    /// A list of css classes applied to this widget.
    pub fn css_classes(self, css_classes: impl Into<glib::StrV>) -> Self {
        Self {
            builder: self.builder.property("css-classes", css_classes.into()),
        }
    }

    /// The name of this widget in the CSS tree.
    ///
    /// This property is meant to be set by widget implementations,
    /// typically in their instance init function.
    pub fn css_name(self, css_name: impl Into<glib::GString>) -> Self {
        Self {
            builder: self.builder.property("css-name", css_name.into()),
        }
    }

    //pub fn cursor(self, cursor: /*Ignored*/&gdk::Cursor) -> Self {
    //    Self { builder: self.builder.property("cursor", cursor), }
    //}

    /// Whether the widget should grab focus when it is clicked with the mouse.
    ///
    /// This property is only relevant for widgets that can take focus.
    pub fn focus_on_click(self, focus_on_click: bool) -> Self {
        Self {
            builder: self.builder.property("focus-on-click", focus_on_click),
        }
    }

    /// Whether this widget itself will accept the input focus.
    pub fn focusable(self, focusable: bool) -> Self {
        Self {
            builder: self.builder.property("focusable", focusable),
        }
    }

    //pub fn halign(self, halign: /*Ignored*/gtk::Align) -> Self {
    //    Self { builder: self.builder.property("halign", halign), }
    //}

    /// Enables or disables the emission of the [`query-tooltip`][struct@crate::gtk::Widget#query-tooltip]
    /// signal on @widget.
    ///
    /// A true value indicates that @widget can have a tooltip, in this case
    /// the widget will be queried using [`query-tooltip`][struct@crate::gtk::Widget#query-tooltip] to
    /// determine whether it will provide a tooltip or not.
    pub fn has_tooltip(self, has_tooltip: bool) -> Self {
        Self {
            builder: self.builder.property("has-tooltip", has_tooltip),
        }
    }

    /// Overrides for height request of the widget.
    ///
    /// If this is -1, the natural request will be used.
    pub fn height_request(self, height_request: i32) -> Self {
        Self {
            builder: self.builder.property("height-request", height_request),
        }
    }

    /// Whether to expand horizontally.
    pub fn hexpand(self, hexpand: bool) -> Self {
        Self {
            builder: self.builder.property("hexpand", hexpand),
        }
    }

    /// Whether to use the `hexpand` property.
    pub fn hexpand_set(self, hexpand_set: bool) -> Self {
        Self {
            builder: self.builder.property("hexpand-set", hexpand_set),
        }
    }

    //pub fn layout_manager(self, layout_manager: &impl IsA</*Ignored*/gtk::LayoutManager>) -> Self {
    //    Self { builder: self.builder.property("layout-manager", layout_manager.clone().upcast()), }
    //}

    /// Makes this widget act like a modal dialog, with respect to
    /// event delivery.
    ///
    /// Global event controllers will not handle events with targets
    /// inside the widget, unless they are set up to ignore propagation
    /// limits. See `Gtk::EventController::set_propagation_limit()`.
    #[cfg(feature = "gtk_v4_18")]
    #[cfg_attr(docsrs, doc(cfg(feature = "gtk_v4_18")))]
    pub fn limit_events(self, limit_events: bool) -> Self {
        Self {
            builder: self.builder.property("limit-events", limit_events),
        }
    }

    /// Margin on end of widget, horizontally.
    ///
    /// This property supports left-to-right and right-to-left text
    /// directions.
    ///
    /// This property adds margin outside of the widget's normal size
    /// request, the margin will be added in addition to the size from
    /// [`WidgetExtManual::set_size_request()`][crate::gtk::prelude::WidgetExtManual::set_size_request()] for example.
    pub fn margin_end(self, margin_end: i32) -> Self {
        Self {
            builder: self.builder.property("margin-end", margin_end),
        }
    }

    /// Margin on start of widget, horizontally.
    ///
    /// This property supports left-to-right and right-to-left text
    /// directions.
    ///
    /// This property adds margin outside of the widget's normal size
    /// request, the margin will be added in addition to the size from
    /// [`WidgetExtManual::set_size_request()`][crate::gtk::prelude::WidgetExtManual::set_size_request()] for example.
    pub fn margin_start(self, margin_start: i32) -> Self {
        Self {
            builder: self.builder.property("margin-start", margin_start),
        }
    }

    /// The name of the widget.
    pub fn name(self, name: impl Into<glib::GString>) -> Self {
        Self {
            builder: self.builder.property("name", name.into()),
        }
    }

    /// The requested opacity of the widget.
    pub fn opacity(self, opacity: f64) -> Self {
        Self {
            builder: self.builder.property("opacity", opacity),
        }
    }

    //pub fn overflow(self, overflow: /*Ignored*/gtk::Overflow) -> Self {
    //    Self { builder: self.builder.property("overflow", overflow), }
    //}

    /// Whether the widget will receive the default action when it is focused.
    pub fn receives_default(self, receives_default: bool) -> Self {
        Self {
            builder: self.builder.property("receives-default", receives_default),
        }
    }

    /// Whether the widget responds to input.
    pub fn sensitive(self, sensitive: bool) -> Self {
        Self {
            builder: self.builder.property("sensitive", sensitive),
        }
    }

    /// Sets the text of tooltip to be the given string, which is marked up
    /// with Pango markup.
    ///
    /// Also see `Gtk::Tooltip::set_markup()`.
    ///
    /// This is a convenience property which will take care of getting the
    /// tooltip shown if the given string is not `NULL`:
    /// [`has-tooltip`][struct@crate::gtk::Widget#has-tooltip] will automatically be set to true
    /// and there will be taken care of [`query-tooltip`][struct@crate::gtk::Widget#query-tooltip] in
    /// the default signal handler.
    ///
    /// Note that if both [`tooltip-text`][struct@crate::gtk::Widget#tooltip-text] and
    /// [`tooltip-markup`][struct@crate::gtk::Widget#tooltip-markup] are set, the last one wins.
    pub fn tooltip_markup(self, tooltip_markup: impl Into<glib::GString>) -> Self {
        Self {
            builder: self
                .builder
                .property("tooltip-markup", tooltip_markup.into()),
        }
    }

    /// Sets the text of tooltip to be the given string.
    ///
    /// Also see `Gtk::Tooltip::set_text()`.
    ///
    /// This is a convenience property which will take care of getting the
    /// tooltip shown if the given string is not `NULL`:
    /// [`has-tooltip`][struct@crate::gtk::Widget#has-tooltip] will automatically be set to true
    /// and there will be taken care of [`query-tooltip`][struct@crate::gtk::Widget#query-tooltip] in
    /// the default signal handler.
    ///
    /// Note that if both [`tooltip-text`][struct@crate::gtk::Widget#tooltip-text] and
    /// [`tooltip-markup`][struct@crate::gtk::Widget#tooltip-markup] are set, the last one wins.
    pub fn tooltip_text(self, tooltip_text: impl Into<glib::GString>) -> Self {
        Self {
            builder: self.builder.property("tooltip-text", tooltip_text.into()),
        }
    }

    //pub fn valign(self, valign: /*Ignored*/gtk::Align) -> Self {
    //    Self { builder: self.builder.property("valign", valign), }
    //}

    /// Whether to expand vertically.
    pub fn vexpand(self, vexpand: bool) -> Self {
        Self {
            builder: self.builder.property("vexpand", vexpand),
        }
    }

    /// Whether to use the `vexpand` property.
    pub fn vexpand_set(self, vexpand_set: bool) -> Self {
        Self {
            builder: self.builder.property("vexpand-set", vexpand_set),
        }
    }

    /// Whether the widget is visible.
    pub fn visible(self, visible: bool) -> Self {
        Self {
            builder: self.builder.property("visible", visible),
        }
    }

    /// Overrides for width request of the widget.
    ///
    /// If this is -1, the natural request will be used.
    pub fn width_request(self, width_request: i32) -> Self {
        Self {
            builder: self.builder.property("width-request", width_request),
        }
    }

    //pub fn accessible_role(self, accessible_role: /*Ignored*/gtk::AccessibleRole) -> Self {
    //    Self { builder: self.builder.property("accessible-role", accessible_role), }
    //}

    // rustdoc-stripper-ignore-next
    /// Build the [`Window`].
    #[must_use = "Building the object from the builder is usually expensive and is not expected to have side effects"]
    pub fn build(self) -> Window {
        assert_initialized_main_thread!();
        self.builder.build()
    }
}

/// Trait containing all [`struct@Window`] methods.
///
/// # Implementors
///
/// [`Window`][struct@crate::Window]
pub trait WindowExt: IsA<Window> + 'static {
    /// Get the current [`gdk::Monitor`][crate::gdk::Monitor] this window resides in.
    #[doc(alias = "astal_window_get_current_monitor")]
    #[doc(alias = "get_current_monitor")]
    fn current_monitor(&self) -> gdk::Monitor {
        unsafe {
            from_glib_full(ffi::astal_window_get_current_monitor(
                self.as_ref().to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "astal_window_get_namespace")]
    #[doc(alias = "get_namespace")]
    fn namespace(&self) -> glib::GString {
        unsafe {
            from_glib_none(ffi::astal_window_get_namespace(
                self.as_ref().to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "astal_window_set_namespace")]
    fn set_namespace(&self, value: &str) {
        unsafe {
            ffi::astal_window_set_namespace(self.as_ref().to_glib_none().0, value.to_glib_none().0);
        }
    }

    #[doc(alias = "astal_window_get_anchor")]
    #[doc(alias = "get_anchor")]
    fn anchor(&self) -> WindowAnchor {
        unsafe { from_glib(ffi::astal_window_get_anchor(self.as_ref().to_glib_none().0)) }
    }

    #[doc(alias = "astal_window_set_anchor")]
    fn set_anchor(&self, value: WindowAnchor) {
        unsafe {
            ffi::astal_window_set_anchor(self.as_ref().to_glib_none().0, value.into_glib());
        }
    }

    #[doc(alias = "astal_window_get_exclusivity")]
    #[doc(alias = "get_exclusivity")]
    fn exclusivity(&self) -> Exclusivity {
        unsafe {
            from_glib(ffi::astal_window_get_exclusivity(
                self.as_ref().to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "astal_window_set_exclusivity")]
    fn set_exclusivity(&self, value: Exclusivity) {
        unsafe {
            ffi::astal_window_set_exclusivity(self.as_ref().to_glib_none().0, value.into_glib());
        }
    }

    #[doc(alias = "astal_window_get_layer")]
    #[doc(alias = "get_layer")]
    fn layer(&self) -> Layer {
        unsafe { from_glib(ffi::astal_window_get_layer(self.as_ref().to_glib_none().0)) }
    }

    #[doc(alias = "astal_window_set_layer")]
    fn set_layer(&self, value: Layer) {
        unsafe {
            ffi::astal_window_set_layer(self.as_ref().to_glib_none().0, value.into_glib());
        }
    }

    #[doc(alias = "astal_window_get_keymode")]
    #[doc(alias = "get_keymode")]
    fn keymode(&self) -> Keymode {
        unsafe {
            from_glib(ffi::astal_window_get_keymode(
                self.as_ref().to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "astal_window_set_keymode")]
    fn set_keymode(&self, value: Keymode) {
        unsafe {
            ffi::astal_window_set_keymode(self.as_ref().to_glib_none().0, value.into_glib());
        }
    }

    #[doc(alias = "astal_window_get_gdkmonitor")]
    #[doc(alias = "get_gdkmonitor")]
    fn gdkmonitor(&self) -> gdk::Monitor {
        unsafe {
            from_glib_none(ffi::astal_window_get_gdkmonitor(
                self.as_ref().to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "astal_window_set_gdkmonitor")]
    fn set_gdkmonitor(&self, value: &gdk::Monitor) {
        unsafe {
            ffi::astal_window_set_gdkmonitor(
                self.as_ref().to_glib_none().0,
                value.to_glib_none().0,
            );
        }
    }

    #[doc(alias = "astal_window_get_margin_top")]
    #[doc(alias = "get_margin_top")]
    fn margin_top(&self) -> i32 {
        unsafe { ffi::astal_window_get_margin_top(self.as_ref().to_glib_none().0) }
    }

    #[doc(alias = "astal_window_set_margin_top")]
    fn set_margin_top(&self, value: i32) {
        unsafe {
            ffi::astal_window_set_margin_top(self.as_ref().to_glib_none().0, value);
        }
    }

    #[doc(alias = "astal_window_get_margin_bottom")]
    #[doc(alias = "get_margin_bottom")]
    fn margin_bottom(&self) -> i32 {
        unsafe { ffi::astal_window_get_margin_bottom(self.as_ref().to_glib_none().0) }
    }

    #[doc(alias = "astal_window_set_margin_bottom")]
    fn set_margin_bottom(&self, value: i32) {
        unsafe {
            ffi::astal_window_set_margin_bottom(self.as_ref().to_glib_none().0, value);
        }
    }

    #[doc(alias = "astal_window_get_margin_left")]
    #[doc(alias = "get_margin_left")]
    fn margin_left(&self) -> i32 {
        unsafe { ffi::astal_window_get_margin_left(self.as_ref().to_glib_none().0) }
    }

    #[doc(alias = "astal_window_set_margin_left")]
    fn set_margin_left(&self, value: i32) {
        unsafe {
            ffi::astal_window_set_margin_left(self.as_ref().to_glib_none().0, value);
        }
    }

    #[doc(alias = "astal_window_get_margin_right")]
    #[doc(alias = "get_margin_right")]
    fn margin_right(&self) -> i32 {
        unsafe { ffi::astal_window_get_margin_right(self.as_ref().to_glib_none().0) }
    }

    #[doc(alias = "astal_window_set_margin_right")]
    fn set_margin_right(&self, value: i32) {
        unsafe {
            ffi::astal_window_set_margin_right(self.as_ref().to_glib_none().0, value);
        }
    }

    #[doc(alias = "astal_window_set_margin")]
    fn set_margin(&self, value: i32) {
        unsafe {
            ffi::astal_window_set_margin(self.as_ref().to_glib_none().0, value);
        }
    }

    #[doc(alias = "astal_window_get_monitor")]
    #[doc(alias = "get_monitor")]
    fn monitor(&self) -> i32 {
        unsafe { ffi::astal_window_get_monitor(self.as_ref().to_glib_none().0) }
    }

    #[doc(alias = "astal_window_set_monitor")]
    fn set_monitor(&self, value: i32) {
        unsafe {
            ffi::astal_window_set_monitor(self.as_ref().to_glib_none().0, value);
        }
    }

    #[doc(alias = "namespace")]
    fn connect_namespace_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_namespace_trampoline<P: IsA<Window>, F: Fn(&P) + 'static>(
            this: *mut ffi::AstalWindow,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(Window::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::namespace".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_namespace_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "anchor")]
    fn connect_anchor_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_anchor_trampoline<P: IsA<Window>, F: Fn(&P) + 'static>(
            this: *mut ffi::AstalWindow,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(Window::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::anchor".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_anchor_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "exclusivity")]
    fn connect_exclusivity_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_exclusivity_trampoline<P: IsA<Window>, F: Fn(&P) + 'static>(
            this: *mut ffi::AstalWindow,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(Window::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::exclusivity".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_exclusivity_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "layer")]
    fn connect_layer_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_layer_trampoline<P: IsA<Window>, F: Fn(&P) + 'static>(
            this: *mut ffi::AstalWindow,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(Window::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::layer".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_layer_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "keymode")]
    fn connect_keymode_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_keymode_trampoline<P: IsA<Window>, F: Fn(&P) + 'static>(
            this: *mut ffi::AstalWindow,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(Window::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::keymode".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_keymode_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "gdkmonitor")]
    fn connect_gdkmonitor_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_gdkmonitor_trampoline<P: IsA<Window>, F: Fn(&P) + 'static>(
            this: *mut ffi::AstalWindow,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(Window::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::gdkmonitor".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_gdkmonitor_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "margin-left")]
    fn connect_margin_left_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_margin_left_trampoline<P: IsA<Window>, F: Fn(&P) + 'static>(
            this: *mut ffi::AstalWindow,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(Window::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::margin-left".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_margin_left_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "margin-right")]
    fn connect_margin_right_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_margin_right_trampoline<P: IsA<Window>, F: Fn(&P) + 'static>(
            this: *mut ffi::AstalWindow,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(Window::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::margin-right".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_margin_right_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "margin")]
    fn connect_margin_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_margin_trampoline<P: IsA<Window>, F: Fn(&P) + 'static>(
            this: *mut ffi::AstalWindow,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(Window::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::margin".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_margin_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "monitor")]
    fn connect_monitor_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_monitor_trampoline<P: IsA<Window>, F: Fn(&P) + 'static>(
            this: *mut ffi::AstalWindow,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(Window::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::monitor".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_monitor_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }
}

impl<O: IsA<Window>> WindowExt for O {}
