// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../../../girs
// from ../../../gtk-girs
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "AstalNiriColumnDisplayTag", sizeof(AstalNiriColumnDisplayTag), alignof(AstalNiriColumnDisplayTag));
    printf("%s;%zu;%zu\n", "AstalNiriLayoutSwitchTargetTag", sizeof(AstalNiriLayoutSwitchTargetTag), alignof(AstalNiriLayoutSwitchTargetTag));
    printf("%s;%zu;%zu\n", "AstalNiriLogicalOutput", sizeof(AstalNiriLogicalOutput), alignof(AstalNiriLogicalOutput));
    printf("%s;%zu;%zu\n", "AstalNiriMode", sizeof(AstalNiriMode), alignof(AstalNiriMode));
    printf("%s;%zu;%zu\n", "AstalNiriNiri", sizeof(AstalNiriNiri), alignof(AstalNiriNiri));
    printf("%s;%zu;%zu\n", "AstalNiriNiriClass", sizeof(AstalNiriNiriClass), alignof(AstalNiriNiriClass));
    printf("%s;%zu;%zu\n", "AstalNiriOutput", sizeof(AstalNiriOutput), alignof(AstalNiriOutput));
    printf("%s;%zu;%zu\n", "AstalNiriOutputClass", sizeof(AstalNiriOutputClass), alignof(AstalNiriOutputClass));
    printf("%s;%zu;%zu\n", "AstalNiriOverview", sizeof(AstalNiriOverview), alignof(AstalNiriOverview));
    printf("%s;%zu;%zu\n", "AstalNiriOverviewClass", sizeof(AstalNiriOverviewClass), alignof(AstalNiriOverviewClass));
    printf("%s;%zu;%zu\n", "AstalNiriPhysicalSize", sizeof(AstalNiriPhysicalSize), alignof(AstalNiriPhysicalSize));
    printf("%s;%zu;%zu\n", "AstalNiriSizeChangeTag", sizeof(AstalNiriSizeChangeTag), alignof(AstalNiriSizeChangeTag));
    printf("%s;%zu;%zu\n", "AstalNiriWindow", sizeof(AstalNiriWindow), alignof(AstalNiriWindow));
    printf("%s;%zu;%zu\n", "AstalNiriWindowClass", sizeof(AstalNiriWindowClass), alignof(AstalNiriWindowClass));
    printf("%s;%zu;%zu\n", "AstalNiriWindowLayout", sizeof(AstalNiriWindowLayout), alignof(AstalNiriWindowLayout));
    printf("%s;%zu;%zu\n", "AstalNiriWorkspace", sizeof(AstalNiriWorkspace), alignof(AstalNiriWorkspace));
    printf("%s;%zu;%zu\n", "AstalNiriWorkspaceClass", sizeof(AstalNiriWorkspaceClass), alignof(AstalNiriWorkspaceClass));
    printf("%s;%zu;%zu\n", "AstalNiriWorkspaceReferenceArgTag", sizeof(AstalNiriWorkspaceReferenceArgTag), alignof(AstalNiriWorkspaceReferenceArgTag));
    printf("%s;%zu;%zu\n", "AstalNirimsg", sizeof(AstalNirimsg), alignof(AstalNirimsg));
    printf("%s;%zu;%zu\n", "AstalNirimsgClass", sizeof(AstalNirimsgClass), alignof(AstalNirimsgClass));
    return 0;
}
