[package]
name = "astal-network-sys"
edition = "2021"
description = "FFI Bindings for libatstal and its libraries"
authors.workspace = true
categories.workspace = true
license.workspace = true
repository.workspace = true
version = "0.1.1"
build = "build.rs"
links = "astal-network"

[package.metadata.system-deps.astal_network]
name = "astal-network-0.1"
version = "0.1"

[package.metadata.docs.rs]
rustc-args = ["--cfg", "docsrs"]
rustdoc-args = ["--cfg", "docsrs", "--generate-link-to-definition"]
all-features = true

[lib]
name = "astal_network_sys"

[dependencies]
libc.workspace = true
nm-rs-sys.workspace = true

[dependencies.glib-sys]
workspace = true

[dependencies.gobject-sys]
workspace = true

[dependencies.gio-sys]
workspace = true

[build-dependencies]
system-deps = "7"

[dev-dependencies]
shell-words = "1.0.0"
tempfile = "3"

[features]
