// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../../girs
// from ../../gtk-girs
// DO NOT EDIT

use crate::{ffi,Loop,PlaybackStatus,Shuffle};
use glib::{prelude::*,signal::{connect_raw, SignalHandlerId},translate::*};
use std::{boxed::Box as Box_};

glib::wrapper! {
    /// Object which tracks players through their mpris DBus interface. The most simple way is to use [`Mpris`][crate::Mpris] which tracks
    /// every player, but [`Player`][crate::Player] can be constructed for dedicated players too.
    ///
    /// ## Properties
    ///
    ///
    /// #### `bus-name`
    ///  Full dbus nama of this player.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `available`
    ///  Indicates if [`bus_name`][struct@crate::Player#bus_name] is available on dbus.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `can-quit`
    ///  Indicates if [`PlayerExt::quit()`][crate::prelude::PlayerExt::quit()] has any effect.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `fullscreen`
    ///  Indicates if the player is occupying the fullscreen. This is typically used for videos. Use [`PlayerExt::toggle_fullscreen()`][crate::prelude::PlayerExt::toggle_fullscreen()]
    /// to toggle fullscreen state.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `can-set-fullscreen`
    ///  Indicates if [`PlayerExt::toggle_fullscreen()`][crate::prelude::PlayerExt::toggle_fullscreen()] has any effect.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `can-raise`
    ///  Indicates if [`PlayerExt::raise()`][crate::prelude::PlayerExt::raise()] has any effect.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `identity`
    ///  A human friendly name to identify the player.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `entry`
    ///  The base name of a .desktop file
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `supported-uri-schemes`
    ///  The URI schemes supported by the media player. This can be viewed as protocols supported by the player in almost all cases. Almost every media
    /// player will include support for the "file" scheme. Other common schemes are "http" and "rtsp".
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `supported-mime-types`
    ///  The mime-types supported by the player.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `loop-status`
    ///  The current loop/repeat status.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `shuffle-status`
    ///  The current shuffle status.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `rate`
    ///  The current playback rate.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `volume`
    ///  The current volume level between 0 and 1 or -1 when it is unsupported.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `position`
    ///  The current position of the track in seconds or -1 when it is unsupported. To get a progress percentage simply divide this with [property
    /// @AstalMpris.Player:length].
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `playback-status`
    ///  The current playback status.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `minimum-rate`
    ///  The minimum value which the [`rate`][struct@crate::Player#rate] can take.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `maximum-rate`
    ///  The maximum value which the [`rate`][struct@crate::Player#rate] can take.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `can-go-next`
    ///  Indicates if invoking [`PlayerExt::next()`][crate::prelude::PlayerExt::next()] has effect.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `can-go-previous`
    ///  Indicates if invoking [`PlayerExt::previous()`][crate::prelude::PlayerExt::previous()] has effect.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `can-play`
    ///  Indicates if invoking [`PlayerExt::play()`][crate::prelude::PlayerExt::play()] has effect.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `can-pause`
    ///  Indicates if invoking [`PlayerExt::pause()`][crate::prelude::PlayerExt::pause()] has effect.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `can-seek`
    ///  Indicates if setting [`position`][struct@crate::Player#position] has effect.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `can-control`
    ///  Indicates if the player can be controlled with methods such as [`PlayerExt::play_pause()`][crate::prelude::PlayerExt::play_pause()].
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `metadata`
    ///  Metadata of this player.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `trackid`
    ///  Currently playing track's id.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `length`
    ///  Length of the currently playing track in seconds.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `art-url`
    ///  The location of an image representing the track or album. You might prefer using [`cover_art`][struct@crate::Player#cover_art].
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `album`
    ///  Title of the currently playing album.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `album-artist`
    ///  Artists of the currently playing album.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `artist`
    ///  Artists of the currently playing track.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `lyrics`
    ///  Lyrics of the currently playing track.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `title`
    ///  Title of the currently playing track.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `composer`
    ///  Composers of the currently playing track.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `comments`
    ///  Comments of the currently playing track.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `cover-art`
    ///  Path of the cached [`art_url`][struct@crate::Player#art_url].
    ///
    /// Readable | Writeable
    ///
    /// # Implements
    ///
    /// [`PlayerExt`][trait@crate::prelude::PlayerExt]
    #[doc(alias = "AstalMprisPlayer")]
    pub struct Player(Object<ffi::AstalMprisPlayer, ffi::AstalMprisPlayerClass>);

    match fn {
        type_ => || ffi::astal_mpris_player_get_type(),
    }
}

impl Player {
        pub const NONE: Option<&'static Player> = None;
    

    /// Construct a Player that tracks a dbus name. For example "org.mpris.MediaPlayer2.spotify". The "org.mpris.MediaPlayer2."
    /// prefix can be omitted so simply "spotify" would mean the same. [`available`][struct@crate::Player#available] indicates whether the player
    /// is actually running or not.
    /// ## `name`
    /// dbus name of the player. 
    #[doc(alias = "astal_mpris_player_new")]
    pub fn new(name: &str) -> Player {
        assert_initialized_main_thread!();
        unsafe {
            from_glib_full(ffi::astal_mpris_player_new(name.to_glib_none().0))
        }
    }

            // rustdoc-stripper-ignore-next
            /// Creates a new builder-pattern struct instance to construct [`Player`] objects.
            ///
            /// This method returns an instance of [`PlayerBuilder`](crate::builders::PlayerBuilder) which can be used to create [`Player`] objects.
            pub fn builder() -> PlayerBuilder {
                PlayerBuilder::new()
            }
        
}

impl Default for Player {
                     fn default() -> Self {
                         glib::object::Object::new::<Self>()
                     }
                 }

// rustdoc-stripper-ignore-next
        /// A [builder-pattern] type to construct [`Player`] objects.
        ///
        /// [builder-pattern]: https://doc.rust-lang.org/1.0.0/style/ownership/builders.html
#[must_use = "The builder must be built to be used"]
pub struct PlayerBuilder {
            builder: glib::object::ObjectBuilder<'static, Player>,
        }

        impl PlayerBuilder {
        fn new() -> Self {
            Self { builder: glib::object::Object::builder() }
        }

                            /// Full dbus nama of this player.
                            pub fn bus_name(self, bus_name: impl Into<glib::GString>) -> Self {
                            Self { builder: self.builder.property("bus-name", bus_name.into()), }
                        }

                            /// Indicates if [`bus_name`][struct@crate::Player#bus_name] is available on dbus.
                            pub fn available(self, available: bool) -> Self {
                            Self { builder: self.builder.property("available", available), }
                        }

                            /// Indicates if [`PlayerExt::quit()`][crate::prelude::PlayerExt::quit()] has any effect.
                            pub fn can_quit(self, can_quit: bool) -> Self {
                            Self { builder: self.builder.property("can-quit", can_quit), }
                        }

                            /// Indicates if the player is occupying the fullscreen. This is typically used for videos. Use [`PlayerExt::toggle_fullscreen()`][crate::prelude::PlayerExt::toggle_fullscreen()]
                            /// to toggle fullscreen state.
                            pub fn fullscreen(self, fullscreen: bool) -> Self {
                            Self { builder: self.builder.property("fullscreen", fullscreen), }
                        }

                            /// Indicates if [`PlayerExt::toggle_fullscreen()`][crate::prelude::PlayerExt::toggle_fullscreen()] has any effect.
                            pub fn can_set_fullscreen(self, can_set_fullscreen: bool) -> Self {
                            Self { builder: self.builder.property("can-set-fullscreen", can_set_fullscreen), }
                        }

                            /// Indicates if [`PlayerExt::raise()`][crate::prelude::PlayerExt::raise()] has any effect.
                            pub fn can_raise(self, can_raise: bool) -> Self {
                            Self { builder: self.builder.property("can-raise", can_raise), }
                        }

                            /// A human friendly name to identify the player.
                            pub fn identity(self, identity: impl Into<glib::GString>) -> Self {
                            Self { builder: self.builder.property("identity", identity.into()), }
                        }

                            /// The base name of a .desktop file
                            pub fn entry(self, entry: impl Into<glib::GString>) -> Self {
                            Self { builder: self.builder.property("entry", entry.into()), }
                        }

                            /// The URI schemes supported by the media player. This can be viewed as protocols supported by the player in almost all cases. Almost every media
                            /// player will include support for the "file" scheme. Other common schemes are "http" and "rtsp".
                            pub fn supported_uri_schemes(self, supported_uri_schemes: impl Into<glib::StrV>) -> Self {
                            Self { builder: self.builder.property("supported-uri-schemes", supported_uri_schemes.into()), }
                        }

                            /// The mime-types supported by the player.
                            pub fn supported_mime_types(self, supported_mime_types: impl Into<glib::StrV>) -> Self {
                            Self { builder: self.builder.property("supported-mime-types", supported_mime_types.into()), }
                        }

                            /// The current loop/repeat status.
                            pub fn loop_status(self, loop_status: Loop) -> Self {
                            Self { builder: self.builder.property("loop-status", loop_status), }
                        }

                            /// The current shuffle status.
                            pub fn shuffle_status(self, shuffle_status: Shuffle) -> Self {
                            Self { builder: self.builder.property("shuffle-status", shuffle_status), }
                        }

                            /// The current playback rate.
                            pub fn rate(self, rate: f64) -> Self {
                            Self { builder: self.builder.property("rate", rate), }
                        }

                            /// The current volume level between 0 and 1 or -1 when it is unsupported.
                            pub fn volume(self, volume: f64) -> Self {
                            Self { builder: self.builder.property("volume", volume), }
                        }

                            /// The current position of the track in seconds or -1 when it is unsupported. To get a progress percentage simply divide this with [property
                            /// @AstalMpris.Player:length].
                            pub fn position(self, position: f64) -> Self {
                            Self { builder: self.builder.property("position", position), }
                        }

                            /// The current playback status.
                            pub fn playback_status(self, playback_status: PlaybackStatus) -> Self {
                            Self { builder: self.builder.property("playback-status", playback_status), }
                        }

                            /// The minimum value which the [`rate`][struct@crate::Player#rate] can take.
                            pub fn minimum_rate(self, minimum_rate: f64) -> Self {
                            Self { builder: self.builder.property("minimum-rate", minimum_rate), }
                        }

                            /// The maximum value which the [`rate`][struct@crate::Player#rate] can take.
                            pub fn maximum_rate(self, maximum_rate: f64) -> Self {
                            Self { builder: self.builder.property("maximum-rate", maximum_rate), }
                        }

                            /// Indicates if invoking [`PlayerExt::next()`][crate::prelude::PlayerExt::next()] has effect.
                            pub fn can_go_next(self, can_go_next: bool) -> Self {
                            Self { builder: self.builder.property("can-go-next", can_go_next), }
                        }

                            /// Indicates if invoking [`PlayerExt::previous()`][crate::prelude::PlayerExt::previous()] has effect.
                            pub fn can_go_previous(self, can_go_previous: bool) -> Self {
                            Self { builder: self.builder.property("can-go-previous", can_go_previous), }
                        }

                            /// Indicates if invoking [`PlayerExt::play()`][crate::prelude::PlayerExt::play()] has effect.
                            pub fn can_play(self, can_play: bool) -> Self {
                            Self { builder: self.builder.property("can-play", can_play), }
                        }

                            /// Indicates if invoking [`PlayerExt::pause()`][crate::prelude::PlayerExt::pause()] has effect.
                            pub fn can_pause(self, can_pause: bool) -> Self {
                            Self { builder: self.builder.property("can-pause", can_pause), }
                        }

                            /// Indicates if setting [`position`][struct@crate::Player#position] has effect.
                            pub fn can_seek(self, can_seek: bool) -> Self {
                            Self { builder: self.builder.property("can-seek", can_seek), }
                        }

                            /// Indicates if the player can be controlled with methods such as [`PlayerExt::play_pause()`][crate::prelude::PlayerExt::play_pause()].
                            pub fn can_control(self, can_control: bool) -> Self {
                            Self { builder: self.builder.property("can-control", can_control), }
                        }

                            /// Metadata of this player.
                            pub fn metadata(self, metadata: &glib::Variant) -> Self {
                            Self { builder: self.builder.property("metadata", metadata.clone()), }
                        }

                            /// Currently playing track's id.
                            pub fn trackid(self, trackid: impl Into<glib::GString>) -> Self {
                            Self { builder: self.builder.property("trackid", trackid.into()), }
                        }

                            /// Length of the currently playing track in seconds.
                            pub fn length(self, length: f64) -> Self {
                            Self { builder: self.builder.property("length", length), }
                        }

                            /// The location of an image representing the track or album. You might prefer using [`cover_art`][struct@crate::Player#cover_art].
                            pub fn art_url(self, art_url: impl Into<glib::GString>) -> Self {
                            Self { builder: self.builder.property("art-url", art_url.into()), }
                        }

                            /// Title of the currently playing album.
                            pub fn album(self, album: impl Into<glib::GString>) -> Self {
                            Self { builder: self.builder.property("album", album.into()), }
                        }

                            /// Artists of the currently playing album.
                            pub fn album_artist(self, album_artist: impl Into<glib::GString>) -> Self {
                            Self { builder: self.builder.property("album-artist", album_artist.into()), }
                        }

                            /// Artists of the currently playing track.
                            pub fn artist(self, artist: impl Into<glib::GString>) -> Self {
                            Self { builder: self.builder.property("artist", artist.into()), }
                        }

                            /// Lyrics of the currently playing track.
                            pub fn lyrics(self, lyrics: impl Into<glib::GString>) -> Self {
                            Self { builder: self.builder.property("lyrics", lyrics.into()), }
                        }

                            /// Title of the currently playing track.
                            pub fn title(self, title: impl Into<glib::GString>) -> Self {
                            Self { builder: self.builder.property("title", title.into()), }
                        }

                            /// Composers of the currently playing track.
                            pub fn composer(self, composer: impl Into<glib::GString>) -> Self {
                            Self { builder: self.builder.property("composer", composer.into()), }
                        }

                            /// Comments of the currently playing track.
                            pub fn comments(self, comments: impl Into<glib::GString>) -> Self {
                            Self { builder: self.builder.property("comments", comments.into()), }
                        }

                            /// Path of the cached [`art_url`][struct@crate::Player#art_url].
                            pub fn cover_art(self, cover_art: impl Into<glib::GString>) -> Self {
                            Self { builder: self.builder.property("cover-art", cover_art.into()), }
                        }

    // rustdoc-stripper-ignore-next
    /// Build the [`Player`].
    #[must_use = "Building the object from the builder is usually expensive and is not expected to have side effects"]
    pub fn build(self) -> Player {
assert_initialized_main_thread!();
    self.builder.build() }
}

/// Trait containing all [`struct@Player`] methods.
///
/// # Implementors
///
/// [`Player`][struct@crate::Player]
pub trait PlayerExt: IsA<Player> + 'static {
    /// Brings the player's user interface to the front using any appropriate mechanism available. The media player may be unable to control how
    /// its user interface is displayed, or it may not have a graphical user interface at all. In this case, the [property@
    /// AstalMpris.Player:can_raise] is `false` and this method does nothing.
    #[doc(alias = "astal_mpris_player_raise")]
    fn raise(&self) {
        unsafe {
            ffi::astal_mpris_player_raise(self.as_ref().to_glib_none().0);
        }
    }

    /// Causes the media player to stop running. The media player may refuse to allow clients to shut it down. In this case, the [property@
    /// AstalMpris.Player:can_quit] property is false and this method does nothing.
    #[doc(alias = "astal_mpris_player_quit")]
    fn quit(&self) {
        unsafe {
            ffi::astal_mpris_player_quit(self.as_ref().to_glib_none().0);
        }
    }

    /// Toggle [`fullscreen`][struct@crate::Player#fullscreen] state.
    #[doc(alias = "astal_mpris_player_toggle_fullscreen")]
    fn toggle_fullscreen(&self) {
        unsafe {
            ffi::astal_mpris_player_toggle_fullscreen(self.as_ref().to_glib_none().0);
        }
    }

    /// Skips to the next track in the tracklist. If there is no next track (and endless playback and track repeat are both off), stop
    /// playback. If [`can_go_next`][struct@crate::Player#can_go_next] is `false` this method has no effect.
    #[doc(alias = "astal_mpris_player_next")]
    fn next(&self) {
        unsafe {
            ffi::astal_mpris_player_next(self.as_ref().to_glib_none().0);
        }
    }

    /// Skips to the previous track in the tracklist. If there is no previous track (and endless playback and track repeat are both off),
    /// stop playback. If [`can_go_previous`][struct@crate::Player#can_go_previous] is `false` this method has no effect.
    #[doc(alias = "astal_mpris_player_previous")]
    fn previous(&self) {
        unsafe {
            ffi::astal_mpris_player_previous(self.as_ref().to_glib_none().0);
        }
    }

    /// Pauses playback. If playback is already paused, this has no effect. If [`can_pause`][struct@crate::Player#can_pause] is `false` this method has
    /// no effect.
    #[doc(alias = "astal_mpris_player_pause")]
    fn pause(&self) {
        unsafe {
            ffi::astal_mpris_player_pause(self.as_ref().to_glib_none().0);
        }
    }

    /// Pauses playback. If playback is already paused, resumes playback. If playback is stopped, starts playback.
    #[doc(alias = "astal_mpris_player_play_pause")]
    fn play_pause(&self) {
        unsafe {
            ffi::astal_mpris_player_play_pause(self.as_ref().to_glib_none().0);
        }
    }

    /// Stops playback. If playback is already stopped, this has no effect. If [`can_control`][struct@crate::Player#can_control] is `false` this method
    /// has no effect.
    #[doc(alias = "astal_mpris_player_stop")]
    fn stop(&self) {
        unsafe {
            ffi::astal_mpris_player_stop(self.as_ref().to_glib_none().0);
        }
    }

    /// Starts or resumes playback. If already playing, this has no effect. If paused, playback resumes from the current position. If [property@
    /// AstalMpris.Player:can_play] is `false` this method has no effect.
    #[doc(alias = "astal_mpris_player_play")]
    fn play(&self) {
        unsafe {
            ffi::astal_mpris_player_play(self.as_ref().to_glib_none().0);
        }
    }

    /// uri scheme should be an element of [`supported_uri_schemes`][struct@crate::Player#supported_uri_schemes] and the mime-type should match one of the elements
    /// of [`supported_mime_types`][struct@crate::Player#supported_mime_types].
    /// ## `uri`
    /// Uri of the track to load. 
    #[doc(alias = "astal_mpris_player_open_uri")]
    fn open_uri(&self, uri: &str) {
        unsafe {
            ffi::astal_mpris_player_open_uri(self.as_ref().to_glib_none().0, uri.to_glib_none().0);
        }
    }

    /// Change [`loop_status`][struct@crate::Player#loop_status] from none to track, from track to playlist, from playlist to none.
    #[doc(alias = "astal_mpris_player_loop")]
    #[doc(alias = "loop")]
    fn loop_(&self) {
        unsafe {
            ffi::astal_mpris_player_loop(self.as_ref().to_glib_none().0);
        }
    }

    /// Toggle [`shuffle_status`][struct@crate::Player#shuffle_status].
    #[doc(alias = "astal_mpris_player_shuffle")]
    fn shuffle(&self) {
        unsafe {
            ffi::astal_mpris_player_shuffle(self.as_ref().to_glib_none().0);
        }
    }

    /// Lookup a key from [`metadata`][struct@crate::Player#metadata]. This method is useful for languages that fail to introspect hashtables.
    #[doc(alias = "astal_mpris_player_get_meta")]
    #[doc(alias = "get_meta")]
    fn meta(&self, key: &str) -> Option<glib::Variant> {
        unsafe {
            from_glib_full(ffi::astal_mpris_player_get_meta(self.as_ref().to_glib_none().0, key.to_glib_none().0))
        }
    }

    #[doc(alias = "astal_mpris_player_get_bus_name")]
    #[doc(alias = "get_bus_name")]
    fn bus_name(&self) -> glib::GString {
        unsafe {
            from_glib_none(ffi::astal_mpris_player_get_bus_name(self.as_ref().to_glib_none().0))
        }
    }

    #[doc(alias = "astal_mpris_player_get_available")]
    #[doc(alias = "get_available")]
    fn is_available(&self) -> bool {
        unsafe {
            from_glib(ffi::astal_mpris_player_get_available(self.as_ref().to_glib_none().0))
        }
    }

    #[doc(alias = "astal_mpris_player_get_can_quit")]
    #[doc(alias = "get_can_quit")]
    fn can_quit(&self) -> bool {
        unsafe {
            from_glib(ffi::astal_mpris_player_get_can_quit(self.as_ref().to_glib_none().0))
        }
    }

    #[doc(alias = "astal_mpris_player_get_fullscreen")]
    #[doc(alias = "get_fullscreen")]
    fn is_fullscreen(&self) -> bool {
        unsafe {
            from_glib(ffi::astal_mpris_player_get_fullscreen(self.as_ref().to_glib_none().0))
        }
    }

    #[doc(alias = "astal_mpris_player_get_can_set_fullscreen")]
    #[doc(alias = "get_can_set_fullscreen")]
    fn can_set_fullscreen(&self) -> bool {
        unsafe {
            from_glib(ffi::astal_mpris_player_get_can_set_fullscreen(self.as_ref().to_glib_none().0))
        }
    }

    #[doc(alias = "astal_mpris_player_get_can_raise")]
    #[doc(alias = "get_can_raise")]
    fn can_raise(&self) -> bool {
        unsafe {
            from_glib(ffi::astal_mpris_player_get_can_raise(self.as_ref().to_glib_none().0))
        }
    }

    #[doc(alias = "astal_mpris_player_get_identity")]
    #[doc(alias = "get_identity")]
    fn identity(&self) -> glib::GString {
        unsafe {
            from_glib_none(ffi::astal_mpris_player_get_identity(self.as_ref().to_glib_none().0))
        }
    }

    #[doc(alias = "astal_mpris_player_get_entry")]
    #[doc(alias = "get_entry")]
    fn entry(&self) -> glib::GString {
        unsafe {
            from_glib_none(ffi::astal_mpris_player_get_entry(self.as_ref().to_glib_none().0))
        }
    }

    #[doc(alias = "astal_mpris_player_get_supported_uri_schemes")]
    #[doc(alias = "get_supported_uri_schemes")]
    fn supported_uri_schemes(&self) -> Vec<glib::GString> {
        unsafe {
            let mut result_length1 = std::mem::MaybeUninit::uninit();
            let ret = FromGlibContainer::from_glib_none_num(ffi::astal_mpris_player_get_supported_uri_schemes(self.as_ref().to_glib_none().0, result_length1.as_mut_ptr()), result_length1.assume_init() as _);
            ret
        }
    }

    #[doc(alias = "astal_mpris_player_get_supported_mime_types")]
    #[doc(alias = "get_supported_mime_types")]
    fn supported_mime_types(&self) -> Vec<glib::GString> {
        unsafe {
            let mut result_length1 = std::mem::MaybeUninit::uninit();
            let ret = FromGlibContainer::from_glib_none_num(ffi::astal_mpris_player_get_supported_mime_types(self.as_ref().to_glib_none().0, result_length1.as_mut_ptr()), result_length1.assume_init() as _);
            ret
        }
    }

    #[doc(alias = "astal_mpris_player_get_loop_status")]
    #[doc(alias = "get_loop_status")]
    fn loop_status(&self) -> Loop {
        unsafe {
            from_glib(ffi::astal_mpris_player_get_loop_status(self.as_ref().to_glib_none().0))
        }
    }

    #[doc(alias = "astal_mpris_player_set_loop_status")]
    fn set_loop_status(&self, value: Loop) {
        unsafe {
            ffi::astal_mpris_player_set_loop_status(self.as_ref().to_glib_none().0, value.into_glib());
        }
    }

    #[doc(alias = "astal_mpris_player_get_shuffle_status")]
    #[doc(alias = "get_shuffle_status")]
    fn shuffle_status(&self) -> Shuffle {
        unsafe {
            from_glib(ffi::astal_mpris_player_get_shuffle_status(self.as_ref().to_glib_none().0))
        }
    }

    #[doc(alias = "astal_mpris_player_set_shuffle_status")]
    fn set_shuffle_status(&self, value: Shuffle) {
        unsafe {
            ffi::astal_mpris_player_set_shuffle_status(self.as_ref().to_glib_none().0, value.into_glib());
        }
    }

    #[doc(alias = "astal_mpris_player_get_rate")]
    #[doc(alias = "get_rate")]
    fn rate(&self) -> f64 {
        unsafe {
            ffi::astal_mpris_player_get_rate(self.as_ref().to_glib_none().0)
        }
    }

    #[doc(alias = "astal_mpris_player_set_rate")]
    fn set_rate(&self, value: f64) {
        unsafe {
            ffi::astal_mpris_player_set_rate(self.as_ref().to_glib_none().0, value);
        }
    }

    #[doc(alias = "astal_mpris_player_get_volume")]
    #[doc(alias = "get_volume")]
    fn volume(&self) -> f64 {
        unsafe {
            ffi::astal_mpris_player_get_volume(self.as_ref().to_glib_none().0)
        }
    }

    #[doc(alias = "astal_mpris_player_set_volume")]
    fn set_volume(&self, value: f64) {
        unsafe {
            ffi::astal_mpris_player_set_volume(self.as_ref().to_glib_none().0, value);
        }
    }

    #[doc(alias = "astal_mpris_player_get_position")]
    #[doc(alias = "get_position")]
    fn position(&self) -> f64 {
        unsafe {
            ffi::astal_mpris_player_get_position(self.as_ref().to_glib_none().0)
        }
    }

    #[doc(alias = "astal_mpris_player_set_position")]
    fn set_position(&self, value: f64) {
        unsafe {
            ffi::astal_mpris_player_set_position(self.as_ref().to_glib_none().0, value);
        }
    }

    #[doc(alias = "astal_mpris_player_get_playback_status")]
    #[doc(alias = "get_playback_status")]
    fn playback_status(&self) -> PlaybackStatus {
        unsafe {
            from_glib(ffi::astal_mpris_player_get_playback_status(self.as_ref().to_glib_none().0))
        }
    }

    #[doc(alias = "astal_mpris_player_get_minimum_rate")]
    #[doc(alias = "get_minimum_rate")]
    fn minimum_rate(&self) -> f64 {
        unsafe {
            ffi::astal_mpris_player_get_minimum_rate(self.as_ref().to_glib_none().0)
        }
    }

    #[doc(alias = "astal_mpris_player_get_maximum_rate")]
    #[doc(alias = "get_maximum_rate")]
    fn maximum_rate(&self) -> f64 {
        unsafe {
            ffi::astal_mpris_player_get_maximum_rate(self.as_ref().to_glib_none().0)
        }
    }

    #[doc(alias = "astal_mpris_player_get_can_go_next")]
    #[doc(alias = "get_can_go_next")]
    fn can_go_next(&self) -> bool {
        unsafe {
            from_glib(ffi::astal_mpris_player_get_can_go_next(self.as_ref().to_glib_none().0))
        }
    }

    #[doc(alias = "astal_mpris_player_get_can_go_previous")]
    #[doc(alias = "get_can_go_previous")]
    fn can_go_previous(&self) -> bool {
        unsafe {
            from_glib(ffi::astal_mpris_player_get_can_go_previous(self.as_ref().to_glib_none().0))
        }
    }

    #[doc(alias = "astal_mpris_player_get_can_play")]
    #[doc(alias = "get_can_play")]
    fn can_play(&self) -> bool {
        unsafe {
            from_glib(ffi::astal_mpris_player_get_can_play(self.as_ref().to_glib_none().0))
        }
    }

    #[doc(alias = "astal_mpris_player_get_can_pause")]
    #[doc(alias = "get_can_pause")]
    fn can_pause(&self) -> bool {
        unsafe {
            from_glib(ffi::astal_mpris_player_get_can_pause(self.as_ref().to_glib_none().0))
        }
    }

    #[doc(alias = "astal_mpris_player_get_can_seek")]
    #[doc(alias = "get_can_seek")]
    fn can_seek(&self) -> bool {
        unsafe {
            from_glib(ffi::astal_mpris_player_get_can_seek(self.as_ref().to_glib_none().0))
        }
    }

    #[doc(alias = "astal_mpris_player_get_can_control")]
    #[doc(alias = "get_can_control")]
    fn can_control(&self) -> bool {
        unsafe {
            from_glib(ffi::astal_mpris_player_get_can_control(self.as_ref().to_glib_none().0))
        }
    }

    #[doc(alias = "astal_mpris_player_get_metadata")]
    #[doc(alias = "get_metadata")]
    fn metadata(&self) -> glib::Variant {
        unsafe {
            from_glib_none(ffi::astal_mpris_player_get_metadata(self.as_ref().to_glib_none().0))
        }
    }

    #[doc(alias = "astal_mpris_player_get_trackid")]
    #[doc(alias = "get_trackid")]
    fn trackid(&self) -> glib::GString {
        unsafe {
            from_glib_none(ffi::astal_mpris_player_get_trackid(self.as_ref().to_glib_none().0))
        }
    }

    #[doc(alias = "astal_mpris_player_get_length")]
    #[doc(alias = "get_length")]
    fn length(&self) -> f64 {
        unsafe {
            ffi::astal_mpris_player_get_length(self.as_ref().to_glib_none().0)
        }
    }

    #[doc(alias = "astal_mpris_player_get_art_url")]
    #[doc(alias = "get_art_url")]
    fn art_url(&self) -> glib::GString {
        unsafe {
            from_glib_none(ffi::astal_mpris_player_get_art_url(self.as_ref().to_glib_none().0))
        }
    }

    #[doc(alias = "astal_mpris_player_get_album")]
    #[doc(alias = "get_album")]
    fn album(&self) -> glib::GString {
        unsafe {
            from_glib_none(ffi::astal_mpris_player_get_album(self.as_ref().to_glib_none().0))
        }
    }

    #[doc(alias = "astal_mpris_player_get_album_artist")]
    #[doc(alias = "get_album_artist")]
    fn album_artist(&self) -> glib::GString {
        unsafe {
            from_glib_none(ffi::astal_mpris_player_get_album_artist(self.as_ref().to_glib_none().0))
        }
    }

    #[doc(alias = "astal_mpris_player_get_artist")]
    #[doc(alias = "get_artist")]
    fn artist(&self) -> glib::GString {
        unsafe {
            from_glib_none(ffi::astal_mpris_player_get_artist(self.as_ref().to_glib_none().0))
        }
    }

    #[doc(alias = "astal_mpris_player_get_lyrics")]
    #[doc(alias = "get_lyrics")]
    fn lyrics(&self) -> glib::GString {
        unsafe {
            from_glib_none(ffi::astal_mpris_player_get_lyrics(self.as_ref().to_glib_none().0))
        }
    }

    #[doc(alias = "astal_mpris_player_get_title")]
    #[doc(alias = "get_title")]
    fn title(&self) -> glib::GString {
        unsafe {
            from_glib_none(ffi::astal_mpris_player_get_title(self.as_ref().to_glib_none().0))
        }
    }

    #[doc(alias = "astal_mpris_player_get_composer")]
    #[doc(alias = "get_composer")]
    fn composer(&self) -> glib::GString {
        unsafe {
            from_glib_none(ffi::astal_mpris_player_get_composer(self.as_ref().to_glib_none().0))
        }
    }

    #[doc(alias = "astal_mpris_player_get_comments")]
    #[doc(alias = "get_comments")]
    fn comments(&self) -> glib::GString {
        unsafe {
            from_glib_none(ffi::astal_mpris_player_get_comments(self.as_ref().to_glib_none().0))
        }
    }

    #[doc(alias = "astal_mpris_player_get_cover_art")]
    #[doc(alias = "get_cover_art")]
    fn cover_art(&self) -> glib::GString {
        unsafe {
            from_glib_none(ffi::astal_mpris_player_get_cover_art(self.as_ref().to_glib_none().0))
        }
    }

    /// Full dbus nama of this player.
    #[doc(alias = "bus-name")]
    fn set_bus_name(&self, bus_name: Option<&str>) {
        ObjectExt::set_property(self.as_ref(),"bus-name", bus_name)
    }

    /// Indicates if [`bus_name`][struct@crate::Player#bus_name] is available on dbus.
    fn set_available(&self, available: bool) {
        ObjectExt::set_property(self.as_ref(),"available", available)
    }

    /// Indicates if [`quit()`][Self::quit()] has any effect.
    #[doc(alias = "can-quit")]
    fn set_can_quit(&self, can_quit: bool) {
        ObjectExt::set_property(self.as_ref(),"can-quit", can_quit)
    }

    /// Indicates if the player is occupying the fullscreen. This is typically used for videos. Use [`toggle_fullscreen()`][Self::toggle_fullscreen()]
    /// to toggle fullscreen state.
    fn set_fullscreen(&self, fullscreen: bool) {
        ObjectExt::set_property(self.as_ref(),"fullscreen", fullscreen)
    }

    /// Indicates if [`toggle_fullscreen()`][Self::toggle_fullscreen()] has any effect.
    #[doc(alias = "can-set-fullscreen")]
    fn set_can_set_fullscreen(&self, can_set_fullscreen: bool) {
        ObjectExt::set_property(self.as_ref(),"can-set-fullscreen", can_set_fullscreen)
    }

    /// Indicates if [`raise()`][Self::raise()] has any effect.
    #[doc(alias = "can-raise")]
    fn set_can_raise(&self, can_raise: bool) {
        ObjectExt::set_property(self.as_ref(),"can-raise", can_raise)
    }

    /// A human friendly name to identify the player.
    fn set_identity(&self, identity: Option<&str>) {
        ObjectExt::set_property(self.as_ref(),"identity", identity)
    }

    /// The base name of a .desktop file
    fn set_entry(&self, entry: Option<&str>) {
        ObjectExt::set_property(self.as_ref(),"entry", entry)
    }

    /// The URI schemes supported by the media player. This can be viewed as protocols supported by the player in almost all cases. Almost every media
    /// player will include support for the "file" scheme. Other common schemes are "http" and "rtsp".
    #[doc(alias = "supported-uri-schemes")]
    fn set_supported_uri_schemes(&self, supported_uri_schemes: &[&str]) {
        ObjectExt::set_property(self.as_ref(),"supported-uri-schemes", supported_uri_schemes)
    }

    /// The mime-types supported by the player.
    #[doc(alias = "supported-mime-types")]
    fn set_supported_mime_types(&self, supported_mime_types: &[&str]) {
        ObjectExt::set_property(self.as_ref(),"supported-mime-types", supported_mime_types)
    }

    /// The current playback status.
    #[doc(alias = "playback-status")]
    fn set_playback_status(&self, playback_status: PlaybackStatus) {
        ObjectExt::set_property(self.as_ref(),"playback-status", playback_status)
    }

    /// The minimum value which the [`rate`][struct@crate::Player#rate] can take.
    #[doc(alias = "minimum-rate")]
    fn set_minimum_rate(&self, minimum_rate: f64) {
        ObjectExt::set_property(self.as_ref(),"minimum-rate", minimum_rate)
    }

    /// The maximum value which the [`rate`][struct@crate::Player#rate] can take.
    #[doc(alias = "maximum-rate")]
    fn set_maximum_rate(&self, maximum_rate: f64) {
        ObjectExt::set_property(self.as_ref(),"maximum-rate", maximum_rate)
    }

    /// Indicates if invoking [`next()`][Self::next()] has effect.
    #[doc(alias = "can-go-next")]
    fn set_can_go_next(&self, can_go_next: bool) {
        ObjectExt::set_property(self.as_ref(),"can-go-next", can_go_next)
    }

    /// Indicates if invoking [`previous()`][Self::previous()] has effect.
    #[doc(alias = "can-go-previous")]
    fn set_can_go_previous(&self, can_go_previous: bool) {
        ObjectExt::set_property(self.as_ref(),"can-go-previous", can_go_previous)
    }

    /// Indicates if invoking [`play()`][Self::play()] has effect.
    #[doc(alias = "can-play")]
    fn set_can_play(&self, can_play: bool) {
        ObjectExt::set_property(self.as_ref(),"can-play", can_play)
    }

    /// Indicates if invoking [`pause()`][Self::pause()] has effect.
    #[doc(alias = "can-pause")]
    fn set_can_pause(&self, can_pause: bool) {
        ObjectExt::set_property(self.as_ref(),"can-pause", can_pause)
    }

    /// Indicates if setting [`position`][struct@crate::Player#position] has effect.
    #[doc(alias = "can-seek")]
    fn set_can_seek(&self, can_seek: bool) {
        ObjectExt::set_property(self.as_ref(),"can-seek", can_seek)
    }

    /// Indicates if the player can be controlled with methods such as [`play_pause()`][Self::play_pause()].
    #[doc(alias = "can-control")]
    fn set_can_control(&self, can_control: bool) {
        ObjectExt::set_property(self.as_ref(),"can-control", can_control)
    }

    /// Metadata of this player.
    fn set_metadata(&self, metadata: Option<&glib::Variant>) {
        ObjectExt::set_property(self.as_ref(),"metadata", metadata)
    }

    /// Currently playing track's id.
    fn set_trackid(&self, trackid: Option<&str>) {
        ObjectExt::set_property(self.as_ref(),"trackid", trackid)
    }

    /// Length of the currently playing track in seconds.
    fn set_length(&self, length: f64) {
        ObjectExt::set_property(self.as_ref(),"length", length)
    }

    /// The location of an image representing the track or album. You might prefer using [`cover_art`][struct@crate::Player#cover_art].
    #[doc(alias = "art-url")]
    fn set_art_url(&self, art_url: Option<&str>) {
        ObjectExt::set_property(self.as_ref(),"art-url", art_url)
    }

    /// Title of the currently playing album.
    fn set_album(&self, album: Option<&str>) {
        ObjectExt::set_property(self.as_ref(),"album", album)
    }

    /// Artists of the currently playing album.
    #[doc(alias = "album-artist")]
    fn set_album_artist(&self, album_artist: Option<&str>) {
        ObjectExt::set_property(self.as_ref(),"album-artist", album_artist)
    }

    /// Artists of the currently playing track.
    fn set_artist(&self, artist: Option<&str>) {
        ObjectExt::set_property(self.as_ref(),"artist", artist)
    }

    /// Lyrics of the currently playing track.
    fn set_lyrics(&self, lyrics: Option<&str>) {
        ObjectExt::set_property(self.as_ref(),"lyrics", lyrics)
    }

    /// Title of the currently playing track.
    fn set_title(&self, title: Option<&str>) {
        ObjectExt::set_property(self.as_ref(),"title", title)
    }

    /// Composers of the currently playing track.
    fn set_composer(&self, composer: Option<&str>) {
        ObjectExt::set_property(self.as_ref(),"composer", composer)
    }

    /// Comments of the currently playing track.
    fn set_comments(&self, comments: Option<&str>) {
        ObjectExt::set_property(self.as_ref(),"comments", comments)
    }

    /// Path of the cached [`art_url`][struct@crate::Player#art_url].
    #[doc(alias = "cover-art")]
    fn set_cover_art(&self, cover_art: Option<&str>) {
        ObjectExt::set_property(self.as_ref(),"cover-art", cover_art)
    }

    #[doc(alias = "bus-name")]
    fn connect_bus_name_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_bus_name_trampoline<P: IsA<Player>, F: Fn(&P) + 'static>(this: *mut ffi::AstalMprisPlayer, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(Player::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::bus-name".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_bus_name_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    #[doc(alias = "available")]
    fn connect_available_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_available_trampoline<P: IsA<Player>, F: Fn(&P) + 'static>(this: *mut ffi::AstalMprisPlayer, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(Player::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::available".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_available_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    #[doc(alias = "can-quit")]
    fn connect_can_quit_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_can_quit_trampoline<P: IsA<Player>, F: Fn(&P) + 'static>(this: *mut ffi::AstalMprisPlayer, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(Player::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::can-quit".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_can_quit_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    #[doc(alias = "fullscreen")]
    fn connect_fullscreen_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_fullscreen_trampoline<P: IsA<Player>, F: Fn(&P) + 'static>(this: *mut ffi::AstalMprisPlayer, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(Player::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::fullscreen".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_fullscreen_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    #[doc(alias = "can-set-fullscreen")]
    fn connect_can_set_fullscreen_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_can_set_fullscreen_trampoline<P: IsA<Player>, F: Fn(&P) + 'static>(this: *mut ffi::AstalMprisPlayer, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(Player::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::can-set-fullscreen".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_can_set_fullscreen_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    #[doc(alias = "can-raise")]
    fn connect_can_raise_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_can_raise_trampoline<P: IsA<Player>, F: Fn(&P) + 'static>(this: *mut ffi::AstalMprisPlayer, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(Player::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::can-raise".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_can_raise_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    #[doc(alias = "identity")]
    fn connect_identity_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_identity_trampoline<P: IsA<Player>, F: Fn(&P) + 'static>(this: *mut ffi::AstalMprisPlayer, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(Player::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::identity".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_identity_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    #[doc(alias = "entry")]
    fn connect_entry_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_entry_trampoline<P: IsA<Player>, F: Fn(&P) + 'static>(this: *mut ffi::AstalMprisPlayer, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(Player::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::entry".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_entry_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    #[doc(alias = "supported-uri-schemes")]
    fn connect_supported_uri_schemes_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_supported_uri_schemes_trampoline<P: IsA<Player>, F: Fn(&P) + 'static>(this: *mut ffi::AstalMprisPlayer, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(Player::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::supported-uri-schemes".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_supported_uri_schemes_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    #[doc(alias = "supported-mime-types")]
    fn connect_supported_mime_types_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_supported_mime_types_trampoline<P: IsA<Player>, F: Fn(&P) + 'static>(this: *mut ffi::AstalMprisPlayer, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(Player::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::supported-mime-types".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_supported_mime_types_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    #[doc(alias = "loop-status")]
    fn connect_loop_status_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_loop_status_trampoline<P: IsA<Player>, F: Fn(&P) + 'static>(this: *mut ffi::AstalMprisPlayer, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(Player::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::loop-status".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_loop_status_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    #[doc(alias = "shuffle-status")]
    fn connect_shuffle_status_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_shuffle_status_trampoline<P: IsA<Player>, F: Fn(&P) + 'static>(this: *mut ffi::AstalMprisPlayer, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(Player::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::shuffle-status".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_shuffle_status_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    #[doc(alias = "rate")]
    fn connect_rate_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_rate_trampoline<P: IsA<Player>, F: Fn(&P) + 'static>(this: *mut ffi::AstalMprisPlayer, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(Player::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::rate".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_rate_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    #[doc(alias = "volume")]
    fn connect_volume_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_volume_trampoline<P: IsA<Player>, F: Fn(&P) + 'static>(this: *mut ffi::AstalMprisPlayer, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(Player::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::volume".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_volume_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    #[doc(alias = "position")]
    fn connect_position_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_position_trampoline<P: IsA<Player>, F: Fn(&P) + 'static>(this: *mut ffi::AstalMprisPlayer, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(Player::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::position".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_position_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    #[doc(alias = "playback-status")]
    fn connect_playback_status_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_playback_status_trampoline<P: IsA<Player>, F: Fn(&P) + 'static>(this: *mut ffi::AstalMprisPlayer, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(Player::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::playback-status".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_playback_status_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    #[doc(alias = "minimum-rate")]
    fn connect_minimum_rate_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_minimum_rate_trampoline<P: IsA<Player>, F: Fn(&P) + 'static>(this: *mut ffi::AstalMprisPlayer, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(Player::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::minimum-rate".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_minimum_rate_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    #[doc(alias = "maximum-rate")]
    fn connect_maximum_rate_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_maximum_rate_trampoline<P: IsA<Player>, F: Fn(&P) + 'static>(this: *mut ffi::AstalMprisPlayer, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(Player::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::maximum-rate".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_maximum_rate_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    #[doc(alias = "can-go-next")]
    fn connect_can_go_next_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_can_go_next_trampoline<P: IsA<Player>, F: Fn(&P) + 'static>(this: *mut ffi::AstalMprisPlayer, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(Player::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::can-go-next".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_can_go_next_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    #[doc(alias = "can-go-previous")]
    fn connect_can_go_previous_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_can_go_previous_trampoline<P: IsA<Player>, F: Fn(&P) + 'static>(this: *mut ffi::AstalMprisPlayer, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(Player::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::can-go-previous".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_can_go_previous_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    #[doc(alias = "can-play")]
    fn connect_can_play_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_can_play_trampoline<P: IsA<Player>, F: Fn(&P) + 'static>(this: *mut ffi::AstalMprisPlayer, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(Player::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::can-play".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_can_play_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    #[doc(alias = "can-pause")]
    fn connect_can_pause_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_can_pause_trampoline<P: IsA<Player>, F: Fn(&P) + 'static>(this: *mut ffi::AstalMprisPlayer, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(Player::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::can-pause".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_can_pause_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    #[doc(alias = "can-seek")]
    fn connect_can_seek_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_can_seek_trampoline<P: IsA<Player>, F: Fn(&P) + 'static>(this: *mut ffi::AstalMprisPlayer, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(Player::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::can-seek".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_can_seek_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    #[doc(alias = "can-control")]
    fn connect_can_control_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_can_control_trampoline<P: IsA<Player>, F: Fn(&P) + 'static>(this: *mut ffi::AstalMprisPlayer, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(Player::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::can-control".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_can_control_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    #[doc(alias = "metadata")]
    fn connect_metadata_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_metadata_trampoline<P: IsA<Player>, F: Fn(&P) + 'static>(this: *mut ffi::AstalMprisPlayer, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(Player::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::metadata".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_metadata_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    #[doc(alias = "trackid")]
    fn connect_trackid_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_trackid_trampoline<P: IsA<Player>, F: Fn(&P) + 'static>(this: *mut ffi::AstalMprisPlayer, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(Player::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::trackid".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_trackid_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    #[doc(alias = "length")]
    fn connect_length_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_length_trampoline<P: IsA<Player>, F: Fn(&P) + 'static>(this: *mut ffi::AstalMprisPlayer, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(Player::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::length".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_length_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    #[doc(alias = "art-url")]
    fn connect_art_url_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_art_url_trampoline<P: IsA<Player>, F: Fn(&P) + 'static>(this: *mut ffi::AstalMprisPlayer, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(Player::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::art-url".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_art_url_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    #[doc(alias = "album")]
    fn connect_album_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_album_trampoline<P: IsA<Player>, F: Fn(&P) + 'static>(this: *mut ffi::AstalMprisPlayer, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(Player::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::album".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_album_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    #[doc(alias = "album-artist")]
    fn connect_album_artist_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_album_artist_trampoline<P: IsA<Player>, F: Fn(&P) + 'static>(this: *mut ffi::AstalMprisPlayer, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(Player::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::album-artist".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_album_artist_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    #[doc(alias = "artist")]
    fn connect_artist_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_artist_trampoline<P: IsA<Player>, F: Fn(&P) + 'static>(this: *mut ffi::AstalMprisPlayer, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(Player::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::artist".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_artist_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    #[doc(alias = "lyrics")]
    fn connect_lyrics_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_lyrics_trampoline<P: IsA<Player>, F: Fn(&P) + 'static>(this: *mut ffi::AstalMprisPlayer, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(Player::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::lyrics".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_lyrics_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    #[doc(alias = "title")]
    fn connect_title_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_title_trampoline<P: IsA<Player>, F: Fn(&P) + 'static>(this: *mut ffi::AstalMprisPlayer, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(Player::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::title".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_title_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    #[doc(alias = "composer")]
    fn connect_composer_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_composer_trampoline<P: IsA<Player>, F: Fn(&P) + 'static>(this: *mut ffi::AstalMprisPlayer, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(Player::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::composer".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_composer_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    #[doc(alias = "comments")]
    fn connect_comments_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_comments_trampoline<P: IsA<Player>, F: Fn(&P) + 'static>(this: *mut ffi::AstalMprisPlayer, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(Player::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::comments".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_comments_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    #[doc(alias = "cover-art")]
    fn connect_cover_art_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_cover_art_trampoline<P: IsA<Player>, F: Fn(&P) + 'static>(this: *mut ffi::AstalMprisPlayer, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(Player::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::cover-art".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_cover_art_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }
}

impl<O: IsA<Player>> PlayerExt for O {}
