// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../../girs
// from ../../gtk-girs
// DO NOT EDIT

mod pam;
pub use self::pam::Pam;

mod constants;
pub use self::constants::VERSION;

pub(crate) mod builders {
    pub use super::pam::PamBuilder;
}
