// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../../girs
// from ../../gtk-girs
// DO NOT EDIT

use crate::{ffi};

glib::wrapper! {
    #[derive(Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
    pub struct Profile(Boxed<ffi::AstalPowerProfilesProfile>);

    match fn {
        copy => |ptr| glib::gobject_ffi::g_boxed_copy(ffi::astal_power_profiles_profile_get_type(), ptr as *mut _) as *mut ffi::AstalPowerProfilesProfile,
        free => |ptr| glib::gobject_ffi::g_boxed_free(ffi::astal_power_profiles_profile_get_type(), ptr as *mut _),
        type_ => || ffi::astal_power_profiles_profile_get_type(),
    }
}
