// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../../girs
// from ../../gtk-girs
// DO NOT EDIT

use crate::{ffi,Device};
use glib::{translate::*};


/// Get the DisplayDevice.
#[doc(alias = "astal_battery_get_default")]
#[doc(alias = "get_default")]
#[allow(clippy::should_implement_trait)]pub fn default() -> Device {
    assert_initialized_main_thread!();
    unsafe {
        from_glib_full(ffi::astal_battery_get_default())
    }
}
