// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../../girs
// from ../../gtk-girs
// DO NOT EDIT

mod device;
pub use self::device::Device;

mod upower;
pub use self::upower::UPower;

mod enums;
pub use self::enums::BatteryLevel;
pub use self::enums::State;
pub use self::enums::Technology;
pub use self::enums::Type;
pub use self::enums::WarningLevel;

pub(crate) mod functions;

mod constants;
pub use self::constants::VERSION;

pub(crate) mod traits {
    pub use super::device::DeviceExt;
    pub use super::upower::UPowerExt;
}
pub(crate) mod builders {
    pub use super::device::DeviceBuilder;
}
