[package]
name = "astal-greet"
authors.workspace = true
categories.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true
readme.workspace = true
description.workspace = true
edition.workspace = true

[dependencies]
astal-greet-sys = { version = "0.1.0", path = "sys" }
glib.workspace = true
