// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../../girs
// from ../../gtk-girs
// DO NOT EDIT

use crate::{ffi};
use glib::{prelude::*,signal::{connect_raw, SignalHandlerId},translate::*};
use std::{boxed::Box as Box_};

glib::wrapper! {
    #[doc(alias = "AstalNiriOverview")]
    pub struct Overview(Object<ffi::AstalNiriOverview, ffi::AstalNiriOverviewClass>);

    match fn {
        type_ => || ffi::astal_niri_overview_get_type(),
    }
}

impl Overview {
        pub const NONE: Option<&'static Overview> = None;
    

    #[doc(alias = "astal_niri_overview_new")]
    pub fn new() -> Overview {
        assert_initialized_main_thread!();
        unsafe {
            from_glib_full(ffi::astal_niri_overview_new())
        }
    }

            // rustdoc-stripper-ignore-next
            /// Creates a new builder-pattern struct instance to construct [`Overview`] objects.
            ///
            /// This method returns an instance of [`OverviewBuilder`](crate::builders::OverviewBuilder) which can be used to create [`Overview`] objects.
            pub fn builder() -> OverviewBuilder {
                OverviewBuilder::new()
            }
        
}

impl Default for Overview {
                     fn default() -> Self {
                         Self::new()
                     }
                 }

// rustdoc-stripper-ignore-next
        /// A [builder-pattern] type to construct [`Overview`] objects.
        ///
        /// [builder-pattern]: https://doc.rust-lang.org/1.0.0/style/ownership/builders.html
#[must_use = "The builder must be built to be used"]
pub struct OverviewBuilder {
            builder: glib::object::ObjectBuilder<'static, Overview>,
        }

        impl OverviewBuilder {
        fn new() -> Self {
            Self { builder: glib::object::Object::builder() }
        }

                            pub fn is_open(self, is_open: bool) -> Self {
                            Self { builder: self.builder.property("is-open", is_open), }
                        }

    // rustdoc-stripper-ignore-next
    /// Build the [`Overview`].
    #[must_use = "Building the object from the builder is usually expensive and is not expected to have side effects"]
    pub fn build(self) -> Overview {
assert_initialized_main_thread!();
    self.builder.build() }
}

pub trait OverviewExt: IsA<Overview> + 'static {
    //#[doc(alias = "astal_niri_overview_toggle")]
    //fn toggle(&self, _callback_: AsyncReadyCallback) {
    //    unsafe { TODO: call ffi:astal_niri_overview_toggle() }
    //}

    #[doc(alias = "astal_niri_overview_get_is_open")]
    #[doc(alias = "get_is_open")]
    fn is_open(&self) -> bool {
        unsafe {
            from_glib(ffi::astal_niri_overview_get_is_open(self.as_ref().to_glib_none().0))
        }
    }

    #[doc(alias = "is-open")]
    fn set_is_open(&self, is_open: bool) {
        ObjectExt::set_property(self.as_ref(),"is-open", is_open)
    }

    #[doc(alias = "is-open")]
    fn connect_is_open_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_is_open_trampoline<P: IsA<Overview>, F: Fn(&P) + 'static>(this: *mut ffi::AstalNiriOverview, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(Overview::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::is-open".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_is_open_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }
}

impl<O: IsA<Overview>> OverviewExt for O {}
