// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../../girs
// from ../../gtk-girs
// DO NOT EDIT

use glib::boxed::Boxed;
use glib::translate::{FromGlibPtrFull, Uninitialized};

use crate::ffi;

glib::wrapper! {
    #[derive(Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
    pub struct WindowLayout(Boxed<ffi::AstalNiriWindowLayout>);

    match fn {
        copy => |ptr| glib::gobject_ffi::g_boxed_copy(ffi::astal_niri_window_layout_get_type(), ptr as *mut _) as *mut ffi::AstalNiriWindowLayout,
        free => |ptr| glib::gobject_ffi::g_boxed_free(ffi::astal_niri_window_layout_get_type(), ptr as *mut _),
        type_ => || ffi::astal_niri_window_layout_get_type(),
    }
}

impl Uninitialized for WindowLayout {
    unsafe fn uninitialized() -> Self {
        let ptr: *mut ffi::AstalNiriWindowLayout = std::ptr::dangling_mut();
        WindowLayout {
            inner: Boxed::from_glib_full(ptr),
        }
    }
}
