// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../../girs
// from ../../gtk-girs
// DO NOT EDIT

use crate::{WindowLayout, Workspace, ffi};
use glib::{
    object::ObjectType as _,
    prelude::*,
    signal::{SignalHandlerId, connect_raw},
    translate::*,
};
use std::boxed::Box as Box_;

glib::wrapper! {
    #[doc(alias = "AstalNiriWindow")]
    pub struct Window(Object<ffi::AstalNiriWindow, ffi::AstalNiriWindowClass>);

    match fn {
        type_ => || ffi::astal_niri_window_get_type(),
    }
}

impl Window {
    pub const NONE: Option<&'static Window> = None;

    #[doc(alias = "astal_niri_window_new")]
    pub fn new() -> Window {
        assert_initialized_main_thread!();
        unsafe { from_glib_full(ffi::astal_niri_window_new()) }
    }
}

impl Default for Window {
    fn default() -> Self {
        Self::new()
    }
}

pub trait WindowExt: IsA<Window> + 'static {
    #[doc(alias = "astal_niri_window_focus")]
    fn focus(&self, id: i32) -> bool {
        unsafe {
            from_glib(ffi::astal_niri_window_focus(
                self.as_ref().to_glib_none().0,
                id,
            ))
        }
    }

    #[doc(alias = "astal_niri_window_set_urgency")]
    fn set_urgency(&self, new_urgency: bool) -> bool {
        unsafe {
            from_glib(ffi::astal_niri_window_set_urgency(
                self.as_ref().to_glib_none().0,
                new_urgency.into_glib(),
            ))
        }
    }

    #[doc(alias = "astal_niri_window_move_to_workspace")]
    fn move_to_workspace(&self, workspace_id: i32, focus: Option<bool>) -> bool {
        unsafe {
            from_glib(ffi::astal_niri_window_move_to_workspace(
                self.as_ref().to_glib_none().0,
                workspace_id,
                if let Some(focus) = focus {
                    focus as i32 as *mut _
                } else {
                    std::ptr::null_mut()
                },
            ))
        }
    }

    #[doc(alias = "astal_niri_window_move_to_monitor")]
    fn move_to_monitor(&self, output: &str) -> bool {
        unsafe {
            from_glib(ffi::astal_niri_window_move_to_monitor(
                self.as_ref().to_glib_none().0,
                output.to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "astal_niri_window_get_id")]
    #[doc(alias = "get_id")]
    fn id(&self) -> u64 {
        unsafe { ffi::astal_niri_window_get_id(self.as_ref().to_glib_none().0) }
    }

    #[doc(alias = "astal_niri_window_get_title")]
    #[doc(alias = "get_title")]
    fn title(&self) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::astal_niri_window_get_title(
                self.as_ref().to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "astal_niri_window_get_app_id")]
    #[doc(alias = "get_app_id")]
    fn app_id(&self) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::astal_niri_window_get_app_id(
                self.as_ref().to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "astal_niri_window_get_workspace_id")]
    #[doc(alias = "get_workspace_id")]
    fn workspace_id(&self) -> u64 {
        unsafe { ffi::astal_niri_window_get_workspace_id(self.as_ref().to_glib_none().0) }
    }

    #[doc(alias = "astal_niri_window_get_is_urgent")]
    #[doc(alias = "get_is_urgent")]
    fn is_urgent(&self) -> bool {
        unsafe {
            from_glib(ffi::astal_niri_window_get_is_urgent(
                self.as_ref().to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "astal_niri_window_get_is_focused")]
    #[doc(alias = "get_is_focused")]
    fn is_focused(&self) -> bool {
        unsafe {
            from_glib(ffi::astal_niri_window_get_is_focused(
                self.as_ref().to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "astal_niri_window_get_is_floating")]
    #[doc(alias = "get_is_floating")]
    fn is_floating(&self) -> bool {
        unsafe {
            from_glib(ffi::astal_niri_window_get_is_floating(
                self.as_ref().to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "astal_niri_window_get_layout")]
    #[doc(alias = "get_layout")]
    fn layout(&self) -> WindowLayout {
        unsafe {
            let mut result = WindowLayout::uninitialized();
            ffi::astal_niri_window_get_layout(
                self.as_ref().to_glib_none().0,
                result.to_glib_none_mut().0,
            );
            result
        }
    }

    #[doc(alias = "astal_niri_window_get_workspace")]
    #[doc(alias = "get_workspace")]
    fn workspace(&self) -> Option<Workspace> {
        unsafe {
            from_glib_none(ffi::astal_niri_window_get_workspace(
                self.as_ref().to_glib_none().0,
            ))
        }
    }

    fn set_id(&self, id: u64) {
        ObjectExt::set_property(self.as_ref(), "id", id)
    }

    fn set_title(&self, title: Option<&str>) {
        ObjectExt::set_property(self.as_ref(), "title", title)
    }

    #[doc(alias = "app-id")]
    fn set_app_id(&self, app_id: Option<&str>) {
        ObjectExt::set_property(self.as_ref(), "app-id", app_id)
    }

    #[doc(alias = "workspace-id")]
    fn set_workspace_id(&self, workspace_id: u64) {
        ObjectExt::set_property(self.as_ref(), "workspace-id", workspace_id)
    }

    #[doc(alias = "is-urgent")]
    fn set_is_urgent(&self, is_urgent: bool) {
        ObjectExt::set_property(self.as_ref(), "is-urgent", is_urgent)
    }

    #[doc(alias = "is-focused")]
    fn set_is_focused(&self, is_focused: bool) {
        ObjectExt::set_property(self.as_ref(), "is-focused", is_focused)
    }

    #[doc(alias = "is-floating")]
    fn set_is_floating(&self, is_floating: bool) {
        ObjectExt::set_property(self.as_ref(), "is-floating", is_floating)
    }

    fn set_layout(&self, layout: Option<&WindowLayout>) {
        ObjectExt::set_property(self.as_ref(), "layout", layout)
    }

    #[doc(alias = "changed")]
    fn connect_changed<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn changed_trampoline<P: IsA<Window>, F: Fn(&P) + 'static>(
            this: *mut ffi::AstalNiriWindow,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(Window::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"changed".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    changed_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "closed")]
    fn connect_closed<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn closed_trampoline<P: IsA<Window>, F: Fn(&P) + 'static>(
            this: *mut ffi::AstalNiriWindow,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(Window::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"closed".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    closed_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "id")]
    fn connect_id_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_id_trampoline<P: IsA<Window>, F: Fn(&P) + 'static>(
            this: *mut ffi::AstalNiriWindow,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(Window::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::id".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_id_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "title")]
    fn connect_title_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_title_trampoline<P: IsA<Window>, F: Fn(&P) + 'static>(
            this: *mut ffi::AstalNiriWindow,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(Window::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::title".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_title_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "app-id")]
    fn connect_app_id_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_app_id_trampoline<P: IsA<Window>, F: Fn(&P) + 'static>(
            this: *mut ffi::AstalNiriWindow,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(Window::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::app-id".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_app_id_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "workspace-id")]
    fn connect_workspace_id_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_workspace_id_trampoline<P: IsA<Window>, F: Fn(&P) + 'static>(
            this: *mut ffi::AstalNiriWindow,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(Window::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::workspace-id".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_workspace_id_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "is-urgent")]
    fn connect_is_urgent_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_is_urgent_trampoline<P: IsA<Window>, F: Fn(&P) + 'static>(
            this: *mut ffi::AstalNiriWindow,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(Window::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::is-urgent".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_is_urgent_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "is-focused")]
    fn connect_is_focused_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_is_focused_trampoline<P: IsA<Window>, F: Fn(&P) + 'static>(
            this: *mut ffi::AstalNiriWindow,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(Window::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::is-focused".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_is_focused_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "is-floating")]
    fn connect_is_floating_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_is_floating_trampoline<P: IsA<Window>, F: Fn(&P) + 'static>(
            this: *mut ffi::AstalNiriWindow,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(Window::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::is-floating".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_is_floating_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "layout")]
    fn connect_layout_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_layout_trampoline<P: IsA<Window>, F: Fn(&P) + 'static>(
            this: *mut ffi::AstalNiriWindow,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(Window::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::layout".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_layout_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "workspace")]
    fn connect_workspace_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_workspace_trampoline<P: IsA<Window>, F: Fn(&P) + 'static>(
            this: *mut ffi::AstalNiriWindow,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(Window::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::workspace".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_workspace_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }
}

impl<O: IsA<Window>> WindowExt for O {}
