// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../../girs
// from ../../gtk-girs
// DO NOT EDIT

use crate::{ffi};
use glib::{prelude::*,translate::*};

#[derive(Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
#[derive(Clone, Copy)]
#[non_exhaustive]
#[doc(alias = "AstalWpAvailable")]
pub enum Available {
    #[doc(alias = "ASTAL_WP_AVAILABLE_UNKNOWN")]
    Unknown,
    #[doc(alias = "ASTAL_WP_AVAILABLE_NO")]
    No,
    #[doc(alias = "ASTAL_WP_AVAILABLE_YES")]
    Yes,
#[doc(hidden)]
    __Unknown(i32),
}

#[doc(hidden)]
impl IntoGlib for Available {
    type GlibType = ffi::AstalWpAvailable;

    #[inline]
fn into_glib(self) -> ffi::AstalWpAvailable {
match self {
            Self::Unknown => ffi::ASTAL_WP_AVAILABLE_UNKNOWN,
            Self::No => ffi::ASTAL_WP_AVAILABLE_NO,
            Self::Yes => ffi::ASTAL_WP_AVAILABLE_YES,
            Self::__Unknown(value) => value,
}
}
}

#[doc(hidden)]
impl FromGlib<ffi::AstalWpAvailable> for Available {
    #[inline]
unsafe fn from_glib(value: ffi::AstalWpAvailable) -> Self {
        skip_assert_initialized!();
        
match value {
            ffi::ASTAL_WP_AVAILABLE_UNKNOWN => Self::Unknown,
            ffi::ASTAL_WP_AVAILABLE_NO => Self::No,
            ffi::ASTAL_WP_AVAILABLE_YES => Self::Yes,
            value => Self::__Unknown(value),
}
}
}

impl StaticType for Available {
                #[inline]
    #[doc(alias = "astal_wp_available_get_type")]
   fn static_type() -> glib::Type {
                    unsafe { from_glib(ffi::astal_wp_available_get_type()) }
                }
            }

impl glib::HasParamSpec for Available {
                type ParamSpec = glib::ParamSpecEnum;
                type SetValue = Self;
                type BuilderFn = fn(&str, Self) -> glib::ParamSpecEnumBuilder<Self>;
    
                fn param_spec_builder() -> Self::BuilderFn {
                    Self::ParamSpec::builder_with_default
                }
}

impl glib::value::ValueType for Available {
    type Type = Self;
}

unsafe impl<'a> glib::value::FromValue<'a> for Available {
    type Checker = glib::value::GenericValueTypeChecker<Self>;

    #[inline]
    unsafe fn from_value(value: &'a glib::Value) -> Self {
        skip_assert_initialized!();
        from_glib(glib::gobject_ffi::g_value_get_enum(value.to_glib_none().0))
    }
}

impl ToValue for Available {
    #[inline]
    fn to_value(&self) -> glib::Value {
        let mut value = glib::Value::for_value_type::<Self>();
        unsafe {
            glib::gobject_ffi::g_value_set_enum(value.to_glib_none_mut().0, self.into_glib());
        }
        value
    }

    #[inline]
    fn value_type(&self) -> glib::Type {
        Self::static_type()
    }
}

impl From<Available> for glib::Value {
    #[inline]
    fn from(v: Available) -> Self {
        skip_assert_initialized!();
        ToValue::to_value(&v)
    }
}

#[derive(Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
#[derive(Clone, Copy)]
#[non_exhaustive]
#[doc(alias = "AstalWpDeviceType")]
pub enum DeviceType {
    #[doc(alias = "ASTAL_WP_DEVICE_TYPE_UNKNOWN")]
    Unknown,
    #[doc(alias = "ASTAL_WP_DEVICE_TYPE_AUDIO")]
    AudioDevice,
    #[doc(alias = "ASTAL_WP_DEVICE_TYPE_VIDEO")]
    VideoDevice,
#[doc(hidden)]
    __Unknown(i32),
}

impl DeviceType {
    #[doc(alias = "astal_wp_device_type_from_string")]
    pub fn from_string(string: &str) -> DeviceType {
        assert_initialized_main_thread!();
        unsafe {
            from_glib(ffi::astal_wp_device_type_from_string(string.to_glib_none().0))
        }
    }

    #[doc(alias = "astal_wp_device_type_to_string")]
    #[doc(alias = "to_string")]
    pub fn to_str(self) -> glib::GString {
        assert_initialized_main_thread!();
        unsafe {
            from_glib_full(ffi::astal_wp_device_type_to_string(self.into_glib()))
        }
    }
}

impl std::fmt::Display for DeviceType {
    #[inline]
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        f.write_str(&self.to_str())
    }
}

#[doc(hidden)]
impl IntoGlib for DeviceType {
    type GlibType = ffi::AstalWpDeviceType;

    #[inline]
fn into_glib(self) -> ffi::AstalWpDeviceType {
match self {
            Self::Unknown => ffi::ASTAL_WP_DEVICE_TYPE_UNKNOWN,
            Self::AudioDevice => ffi::ASTAL_WP_DEVICE_TYPE_AUDIO,
            Self::VideoDevice => ffi::ASTAL_WP_DEVICE_TYPE_VIDEO,
            Self::__Unknown(value) => value,
}
}
}

#[doc(hidden)]
impl FromGlib<ffi::AstalWpDeviceType> for DeviceType {
    #[inline]
unsafe fn from_glib(value: ffi::AstalWpDeviceType) -> Self {
        skip_assert_initialized!();
        
match value {
            ffi::ASTAL_WP_DEVICE_TYPE_UNKNOWN => Self::Unknown,
            ffi::ASTAL_WP_DEVICE_TYPE_AUDIO => Self::AudioDevice,
            ffi::ASTAL_WP_DEVICE_TYPE_VIDEO => Self::VideoDevice,
            value => Self::__Unknown(value),
}
}
}

impl StaticType for DeviceType {
                #[inline]
    #[doc(alias = "astal_wp_device_type_get_type")]
   fn static_type() -> glib::Type {
                    unsafe { from_glib(ffi::astal_wp_device_type_get_type()) }
                }
            }

impl glib::HasParamSpec for DeviceType {
                type ParamSpec = glib::ParamSpecEnum;
                type SetValue = Self;
                type BuilderFn = fn(&str, Self) -> glib::ParamSpecEnumBuilder<Self>;
    
                fn param_spec_builder() -> Self::BuilderFn {
                    Self::ParamSpec::builder_with_default
                }
}

impl glib::value::ValueType for DeviceType {
    type Type = Self;
}

unsafe impl<'a> glib::value::FromValue<'a> for DeviceType {
    type Checker = glib::value::GenericValueTypeChecker<Self>;

    #[inline]
    unsafe fn from_value(value: &'a glib::Value) -> Self {
        skip_assert_initialized!();
        from_glib(glib::gobject_ffi::g_value_get_enum(value.to_glib_none().0))
    }
}

impl ToValue for DeviceType {
    #[inline]
    fn to_value(&self) -> glib::Value {
        let mut value = glib::Value::for_value_type::<Self>();
        unsafe {
            glib::gobject_ffi::g_value_set_enum(value.to_glib_none_mut().0, self.into_glib());
        }
        value
    }

    #[inline]
    fn value_type(&self) -> glib::Type {
        Self::static_type()
    }
}

impl From<DeviceType> for glib::Value {
    #[inline]
    fn from(v: DeviceType) -> Self {
        skip_assert_initialized!();
        ToValue::to_value(&v)
    }
}

#[derive(Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
#[derive(Clone, Copy)]
#[non_exhaustive]
#[doc(alias = "AstalWpDirection")]
pub enum Direction {
    #[doc(alias = "ASTAL_WP_DIRECTION_INPUT")]
    Input,
    #[doc(alias = "ASTAL_WP_DIRECTION_OUTPUT")]
    Output,
#[doc(hidden)]
    __Unknown(i32),
}

#[doc(hidden)]
impl IntoGlib for Direction {
    type GlibType = ffi::AstalWpDirection;

    #[inline]
fn into_glib(self) -> ffi::AstalWpDirection {
match self {
            Self::Input => ffi::ASTAL_WP_DIRECTION_INPUT,
            Self::Output => ffi::ASTAL_WP_DIRECTION_OUTPUT,
            Self::__Unknown(value) => value,
}
}
}

#[doc(hidden)]
impl FromGlib<ffi::AstalWpDirection> for Direction {
    #[inline]
unsafe fn from_glib(value: ffi::AstalWpDirection) -> Self {
        skip_assert_initialized!();
        
match value {
            ffi::ASTAL_WP_DIRECTION_INPUT => Self::Input,
            ffi::ASTAL_WP_DIRECTION_OUTPUT => Self::Output,
            value => Self::__Unknown(value),
}
}
}

impl StaticType for Direction {
                #[inline]
    #[doc(alias = "astal_wp_direction_get_type")]
   fn static_type() -> glib::Type {
                    unsafe { from_glib(ffi::astal_wp_direction_get_type()) }
                }
            }

impl glib::HasParamSpec for Direction {
                type ParamSpec = glib::ParamSpecEnum;
                type SetValue = Self;
                type BuilderFn = fn(&str, Self) -> glib::ParamSpecEnumBuilder<Self>;
    
                fn param_spec_builder() -> Self::BuilderFn {
                    Self::ParamSpec::builder_with_default
                }
}

impl glib::value::ValueType for Direction {
    type Type = Self;
}

unsafe impl<'a> glib::value::FromValue<'a> for Direction {
    type Checker = glib::value::GenericValueTypeChecker<Self>;

    #[inline]
    unsafe fn from_value(value: &'a glib::Value) -> Self {
        skip_assert_initialized!();
        from_glib(glib::gobject_ffi::g_value_get_enum(value.to_glib_none().0))
    }
}

impl ToValue for Direction {
    #[inline]
    fn to_value(&self) -> glib::Value {
        let mut value = glib::Value::for_value_type::<Self>();
        unsafe {
            glib::gobject_ffi::g_value_set_enum(value.to_glib_none_mut().0, self.into_glib());
        }
        value
    }

    #[inline]
    fn value_type(&self) -> glib::Type {
        Self::static_type()
    }
}

impl From<Direction> for glib::Value {
    #[inline]
    fn from(v: Direction) -> Self {
        skip_assert_initialized!();
        ToValue::to_value(&v)
    }
}

#[derive(Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
#[derive(Clone, Copy)]
#[non_exhaustive]
#[doc(alias = "AstalWpMediaCategory")]
pub enum MediaCategory {
    #[doc(alias = "ASTAL_WP_MEDIA_CATEGORY_UNKNOWN")]
    Unknown,
    #[doc(alias = "ASTAL_WP_MEDIA_CATEGORY_PLAYBACK")]
    Playback,
    #[doc(alias = "ASTAL_WP_MEDIA_CATEGORY_CAPTURE")]
    Capture,
    #[doc(alias = "ASTAL_WP_MEDIA_CATEGORY_DUPLEX")]
    Duplex,
    #[doc(alias = "ASTAL_WP_MEDIA_CATEGORY_MONITOR")]
    Monitor,
    #[doc(alias = "ASTAL_WP_MEDIA_CATEGORY_MANAGER")]
    Manager,
#[doc(hidden)]
    __Unknown(i32),
}

impl MediaCategory {
    #[doc(alias = "astal_wp_media_category_from_string")]
    pub fn from_string(string: &str) -> MediaCategory {
        assert_initialized_main_thread!();
        unsafe {
            from_glib(ffi::astal_wp_media_category_from_string(string.to_glib_none().0))
        }
    }

    #[doc(alias = "astal_wp_media_category_to_string")]
    #[doc(alias = "to_string")]
    pub fn to_str(self) -> glib::GString {
        assert_initialized_main_thread!();
        unsafe {
            from_glib_full(ffi::astal_wp_media_category_to_string(self.into_glib()))
        }
    }
}

impl std::fmt::Display for MediaCategory {
    #[inline]
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        f.write_str(&self.to_str())
    }
}

#[doc(hidden)]
impl IntoGlib for MediaCategory {
    type GlibType = ffi::AstalWpMediaCategory;

    #[inline]
fn into_glib(self) -> ffi::AstalWpMediaCategory {
match self {
            Self::Unknown => ffi::ASTAL_WP_MEDIA_CATEGORY_UNKNOWN,
            Self::Playback => ffi::ASTAL_WP_MEDIA_CATEGORY_PLAYBACK,
            Self::Capture => ffi::ASTAL_WP_MEDIA_CATEGORY_CAPTURE,
            Self::Duplex => ffi::ASTAL_WP_MEDIA_CATEGORY_DUPLEX,
            Self::Monitor => ffi::ASTAL_WP_MEDIA_CATEGORY_MONITOR,
            Self::Manager => ffi::ASTAL_WP_MEDIA_CATEGORY_MANAGER,
            Self::__Unknown(value) => value,
}
}
}

#[doc(hidden)]
impl FromGlib<ffi::AstalWpMediaCategory> for MediaCategory {
    #[inline]
unsafe fn from_glib(value: ffi::AstalWpMediaCategory) -> Self {
        skip_assert_initialized!();
        
match value {
            ffi::ASTAL_WP_MEDIA_CATEGORY_UNKNOWN => Self::Unknown,
            ffi::ASTAL_WP_MEDIA_CATEGORY_PLAYBACK => Self::Playback,
            ffi::ASTAL_WP_MEDIA_CATEGORY_CAPTURE => Self::Capture,
            ffi::ASTAL_WP_MEDIA_CATEGORY_DUPLEX => Self::Duplex,
            ffi::ASTAL_WP_MEDIA_CATEGORY_MONITOR => Self::Monitor,
            ffi::ASTAL_WP_MEDIA_CATEGORY_MANAGER => Self::Manager,
            value => Self::__Unknown(value),
}
}
}

impl StaticType for MediaCategory {
                #[inline]
    #[doc(alias = "astal_wp_media_category_get_type")]
   fn static_type() -> glib::Type {
                    unsafe { from_glib(ffi::astal_wp_media_category_get_type()) }
                }
            }

impl glib::HasParamSpec for MediaCategory {
                type ParamSpec = glib::ParamSpecEnum;
                type SetValue = Self;
                type BuilderFn = fn(&str, Self) -> glib::ParamSpecEnumBuilder<Self>;
    
                fn param_spec_builder() -> Self::BuilderFn {
                    Self::ParamSpec::builder_with_default
                }
}

impl glib::value::ValueType for MediaCategory {
    type Type = Self;
}

unsafe impl<'a> glib::value::FromValue<'a> for MediaCategory {
    type Checker = glib::value::GenericValueTypeChecker<Self>;

    #[inline]
    unsafe fn from_value(value: &'a glib::Value) -> Self {
        skip_assert_initialized!();
        from_glib(glib::gobject_ffi::g_value_get_enum(value.to_glib_none().0))
    }
}

impl ToValue for MediaCategory {
    #[inline]
    fn to_value(&self) -> glib::Value {
        let mut value = glib::Value::for_value_type::<Self>();
        unsafe {
            glib::gobject_ffi::g_value_set_enum(value.to_glib_none_mut().0, self.into_glib());
        }
        value
    }

    #[inline]
    fn value_type(&self) -> glib::Type {
        Self::static_type()
    }
}

impl From<MediaCategory> for glib::Value {
    #[inline]
    fn from(v: MediaCategory) -> Self {
        skip_assert_initialized!();
        ToValue::to_value(&v)
    }
}

#[derive(Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
#[derive(Clone, Copy)]
#[non_exhaustive]
#[doc(alias = "AstalWpMediaClass")]
pub enum MediaClass {
    #[doc(alias = "ASTAL_WP_MEDIA_CLASS_UNKNOWN")]
    Unknown,
    #[doc(alias = "ASTAL_WP_MEDIA_CLASS_AUDIO_MICROPHONE")]
    AudioSource,
    #[doc(alias = "ASTAL_WP_MEDIA_CLASS_AUDIO_SPEAKER")]
    AudioSink,
    #[doc(alias = "ASTAL_WP_MEDIA_CLASS_AUDIO_RECORDER")]
    StreamInputAudio,
    #[doc(alias = "ASTAL_WP_MEDIA_CLASS_AUDIO_STREAM")]
    StreamOutputAudio,
    #[doc(alias = "ASTAL_WP_MEDIA_CLASS_VIDEO_SOURCE")]
    VideoSource,
    #[doc(alias = "ASTAL_WP_MEDIA_CLASS_VIDEO_SINK")]
    VideoSink,
    #[doc(alias = "ASTAL_WP_MEDIA_CLASS_VIDEO_RECORDER")]
    StreamInputVideo,
    #[doc(alias = "ASTAL_WP_MEDIA_CLASS_VIDEO_STREAM")]
    StreamOutputVideo,
#[doc(hidden)]
    __Unknown(i32),
}

impl MediaClass {
    #[doc(alias = "astal_wp_media_class_from_string")]
    pub fn from_string(string: &str) -> MediaClass {
        assert_initialized_main_thread!();
        unsafe {
            from_glib(ffi::astal_wp_media_class_from_string(string.to_glib_none().0))
        }
    }

    #[doc(alias = "astal_wp_media_class_to_string")]
    #[doc(alias = "to_string")]
    pub fn to_str(self) -> glib::GString {
        assert_initialized_main_thread!();
        unsafe {
            from_glib_full(ffi::astal_wp_media_class_to_string(self.into_glib()))
        }
    }
}

impl std::fmt::Display for MediaClass {
    #[inline]
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        f.write_str(&self.to_str())
    }
}

#[doc(hidden)]
impl IntoGlib for MediaClass {
    type GlibType = ffi::AstalWpMediaClass;

    #[inline]
fn into_glib(self) -> ffi::AstalWpMediaClass {
match self {
            Self::Unknown => ffi::ASTAL_WP_MEDIA_CLASS_UNKNOWN,
            Self::AudioSource => ffi::ASTAL_WP_MEDIA_CLASS_AUDIO_MICROPHONE,
            Self::AudioSink => ffi::ASTAL_WP_MEDIA_CLASS_AUDIO_SPEAKER,
            Self::StreamInputAudio => ffi::ASTAL_WP_MEDIA_CLASS_AUDIO_RECORDER,
            Self::StreamOutputAudio => ffi::ASTAL_WP_MEDIA_CLASS_AUDIO_STREAM,
            Self::VideoSource => ffi::ASTAL_WP_MEDIA_CLASS_VIDEO_SOURCE,
            Self::VideoSink => ffi::ASTAL_WP_MEDIA_CLASS_VIDEO_SINK,
            Self::StreamInputVideo => ffi::ASTAL_WP_MEDIA_CLASS_VIDEO_RECORDER,
            Self::StreamOutputVideo => ffi::ASTAL_WP_MEDIA_CLASS_VIDEO_STREAM,
            Self::__Unknown(value) => value,
}
}
}

#[doc(hidden)]
impl FromGlib<ffi::AstalWpMediaClass> for MediaClass {
    #[inline]
unsafe fn from_glib(value: ffi::AstalWpMediaClass) -> Self {
        skip_assert_initialized!();
        
match value {
            ffi::ASTAL_WP_MEDIA_CLASS_UNKNOWN => Self::Unknown,
            ffi::ASTAL_WP_MEDIA_CLASS_AUDIO_MICROPHONE => Self::AudioSource,
            ffi::ASTAL_WP_MEDIA_CLASS_AUDIO_SPEAKER => Self::AudioSink,
            ffi::ASTAL_WP_MEDIA_CLASS_AUDIO_RECORDER => Self::StreamInputAudio,
            ffi::ASTAL_WP_MEDIA_CLASS_AUDIO_STREAM => Self::StreamOutputAudio,
            ffi::ASTAL_WP_MEDIA_CLASS_VIDEO_SOURCE => Self::VideoSource,
            ffi::ASTAL_WP_MEDIA_CLASS_VIDEO_SINK => Self::VideoSink,
            ffi::ASTAL_WP_MEDIA_CLASS_VIDEO_RECORDER => Self::StreamInputVideo,
            ffi::ASTAL_WP_MEDIA_CLASS_VIDEO_STREAM => Self::StreamOutputVideo,
            value => Self::__Unknown(value),
}
}
}

impl StaticType for MediaClass {
                #[inline]
    #[doc(alias = "astal_wp_media_class_get_type")]
   fn static_type() -> glib::Type {
                    unsafe { from_glib(ffi::astal_wp_media_class_get_type()) }
                }
            }

impl glib::HasParamSpec for MediaClass {
                type ParamSpec = glib::ParamSpecEnum;
                type SetValue = Self;
                type BuilderFn = fn(&str, Self) -> glib::ParamSpecEnumBuilder<Self>;
    
                fn param_spec_builder() -> Self::BuilderFn {
                    Self::ParamSpec::builder_with_default
                }
}

impl glib::value::ValueType for MediaClass {
    type Type = Self;
}

unsafe impl<'a> glib::value::FromValue<'a> for MediaClass {
    type Checker = glib::value::GenericValueTypeChecker<Self>;

    #[inline]
    unsafe fn from_value(value: &'a glib::Value) -> Self {
        skip_assert_initialized!();
        from_glib(glib::gobject_ffi::g_value_get_enum(value.to_glib_none().0))
    }
}

impl ToValue for MediaClass {
    #[inline]
    fn to_value(&self) -> glib::Value {
        let mut value = glib::Value::for_value_type::<Self>();
        unsafe {
            glib::gobject_ffi::g_value_set_enum(value.to_glib_none_mut().0, self.into_glib());
        }
        value
    }

    #[inline]
    fn value_type(&self) -> glib::Type {
        Self::static_type()
    }
}

impl From<MediaClass> for glib::Value {
    #[inline]
    fn from(v: MediaClass) -> Self {
        skip_assert_initialized!();
        ToValue::to_value(&v)
    }
}

#[derive(Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
#[derive(Clone, Copy)]
#[non_exhaustive]
#[doc(alias = "AstalWpMediaRole")]
pub enum MediaRole {
    #[doc(alias = "ASTAL_WP_MEDIA_ROLE_UNKNOWN")]
    Unknown,
    #[doc(alias = "ASTAL_WP_MEDIA_ROLE_MOVIE")]
    Movie,
    #[doc(alias = "ASTAL_WP_MEDIA_ROLE_MUSIC")]
    Music,
    #[doc(alias = "ASTAL_WP_MEDIA_ROLE_CAMERA")]
    Camera,
    #[doc(alias = "ASTAL_WP_MEDIA_ROLE_SCREEN")]
    Screen,
    #[doc(alias = "ASTAL_WP_MEDIA_ROLE_COMMUNICATION")]
    Communication,
    #[doc(alias = "ASTAL_WP_MEDIA_ROLE_GAME")]
    Game,
    #[doc(alias = "ASTAL_WP_MEDIA_ROLE_NOTIFICATION")]
    Notification,
    #[doc(alias = "ASTAL_WP_MEDIA_ROLE_DSP")]
    DSP,
    #[doc(alias = "ASTAL_WP_MEDIA_ROLE_PRODUCTION")]
    Production,
    #[doc(alias = "ASTAL_WP_MEDIA_ROLE_ACCESSIBILITY")]
    Accessibility,
    #[doc(alias = "ASTAL_WP_MEDIA_ROLE_TEST")]
    Test,
#[doc(hidden)]
    __Unknown(i32),
}

impl MediaRole {
    #[doc(alias = "astal_wp_media_role_from_string")]
    pub fn from_string(string: &str) -> MediaRole {
        assert_initialized_main_thread!();
        unsafe {
            from_glib(ffi::astal_wp_media_role_from_string(string.to_glib_none().0))
        }
    }

    #[doc(alias = "astal_wp_media_role_to_string")]
    #[doc(alias = "to_string")]
    pub fn to_str(self) -> glib::GString {
        assert_initialized_main_thread!();
        unsafe {
            from_glib_full(ffi::astal_wp_media_role_to_string(self.into_glib()))
        }
    }
}

impl std::fmt::Display for MediaRole {
    #[inline]
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        f.write_str(&self.to_str())
    }
}

#[doc(hidden)]
impl IntoGlib for MediaRole {
    type GlibType = ffi::AstalWpMediaRole;

    #[inline]
fn into_glib(self) -> ffi::AstalWpMediaRole {
match self {
            Self::Unknown => ffi::ASTAL_WP_MEDIA_ROLE_UNKNOWN,
            Self::Movie => ffi::ASTAL_WP_MEDIA_ROLE_MOVIE,
            Self::Music => ffi::ASTAL_WP_MEDIA_ROLE_MUSIC,
            Self::Camera => ffi::ASTAL_WP_MEDIA_ROLE_CAMERA,
            Self::Screen => ffi::ASTAL_WP_MEDIA_ROLE_SCREEN,
            Self::Communication => ffi::ASTAL_WP_MEDIA_ROLE_COMMUNICATION,
            Self::Game => ffi::ASTAL_WP_MEDIA_ROLE_GAME,
            Self::Notification => ffi::ASTAL_WP_MEDIA_ROLE_NOTIFICATION,
            Self::DSP => ffi::ASTAL_WP_MEDIA_ROLE_DSP,
            Self::Production => ffi::ASTAL_WP_MEDIA_ROLE_PRODUCTION,
            Self::Accessibility => ffi::ASTAL_WP_MEDIA_ROLE_ACCESSIBILITY,
            Self::Test => ffi::ASTAL_WP_MEDIA_ROLE_TEST,
            Self::__Unknown(value) => value,
}
}
}

#[doc(hidden)]
impl FromGlib<ffi::AstalWpMediaRole> for MediaRole {
    #[inline]
unsafe fn from_glib(value: ffi::AstalWpMediaRole) -> Self {
        skip_assert_initialized!();
        
match value {
            ffi::ASTAL_WP_MEDIA_ROLE_UNKNOWN => Self::Unknown,
            ffi::ASTAL_WP_MEDIA_ROLE_MOVIE => Self::Movie,
            ffi::ASTAL_WP_MEDIA_ROLE_MUSIC => Self::Music,
            ffi::ASTAL_WP_MEDIA_ROLE_CAMERA => Self::Camera,
            ffi::ASTAL_WP_MEDIA_ROLE_SCREEN => Self::Screen,
            ffi::ASTAL_WP_MEDIA_ROLE_COMMUNICATION => Self::Communication,
            ffi::ASTAL_WP_MEDIA_ROLE_GAME => Self::Game,
            ffi::ASTAL_WP_MEDIA_ROLE_NOTIFICATION => Self::Notification,
            ffi::ASTAL_WP_MEDIA_ROLE_DSP => Self::DSP,
            ffi::ASTAL_WP_MEDIA_ROLE_PRODUCTION => Self::Production,
            ffi::ASTAL_WP_MEDIA_ROLE_ACCESSIBILITY => Self::Accessibility,
            ffi::ASTAL_WP_MEDIA_ROLE_TEST => Self::Test,
            value => Self::__Unknown(value),
}
}
}

impl StaticType for MediaRole {
                #[inline]
    #[doc(alias = "astal_wp_media_role_get_type")]
   fn static_type() -> glib::Type {
                    unsafe { from_glib(ffi::astal_wp_media_role_get_type()) }
                }
            }

impl glib::HasParamSpec for MediaRole {
                type ParamSpec = glib::ParamSpecEnum;
                type SetValue = Self;
                type BuilderFn = fn(&str, Self) -> glib::ParamSpecEnumBuilder<Self>;
    
                fn param_spec_builder() -> Self::BuilderFn {
                    Self::ParamSpec::builder_with_default
                }
}

impl glib::value::ValueType for MediaRole {
    type Type = Self;
}

unsafe impl<'a> glib::value::FromValue<'a> for MediaRole {
    type Checker = glib::value::GenericValueTypeChecker<Self>;

    #[inline]
    unsafe fn from_value(value: &'a glib::Value) -> Self {
        skip_assert_initialized!();
        from_glib(glib::gobject_ffi::g_value_get_enum(value.to_glib_none().0))
    }
}

impl ToValue for MediaRole {
    #[inline]
    fn to_value(&self) -> glib::Value {
        let mut value = glib::Value::for_value_type::<Self>();
        unsafe {
            glib::gobject_ffi::g_value_set_enum(value.to_glib_none_mut().0, self.into_glib());
        }
        value
    }

    #[inline]
    fn value_type(&self) -> glib::Type {
        Self::static_type()
    }
}

impl From<MediaRole> for glib::Value {
    #[inline]
    fn from(v: MediaRole) -> Self {
        skip_assert_initialized!();
        ToValue::to_value(&v)
    }
}

#[derive(Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
#[derive(Clone, Copy)]
#[non_exhaustive]
#[doc(alias = "AstalWpNodeState")]
pub enum NodeState {
    #[doc(alias = "ASTAL_WP_NODE_STATE_ERROR")]
    Error,
    #[doc(alias = "ASTAL_WP_NODE_STATE_CREATING")]
    Creating,
    #[doc(alias = "ASTAL_WP_NODE_STATE_SUSPENDED")]
    Suspended,
    #[doc(alias = "ASTAL_WP_NODE_STATE_IDLE")]
    Idle,
    #[doc(alias = "ASTAL_WP_NODE_STATE_RUNNING")]
    Running,
#[doc(hidden)]
    __Unknown(i32),
}

#[doc(hidden)]
impl IntoGlib for NodeState {
    type GlibType = ffi::AstalWpNodeState;

    #[inline]
fn into_glib(self) -> ffi::AstalWpNodeState {
match self {
            Self::Error => ffi::ASTAL_WP_NODE_STATE_ERROR,
            Self::Creating => ffi::ASTAL_WP_NODE_STATE_CREATING,
            Self::Suspended => ffi::ASTAL_WP_NODE_STATE_SUSPENDED,
            Self::Idle => ffi::ASTAL_WP_NODE_STATE_IDLE,
            Self::Running => ffi::ASTAL_WP_NODE_STATE_RUNNING,
            Self::__Unknown(value) => value,
}
}
}

#[doc(hidden)]
impl FromGlib<ffi::AstalWpNodeState> for NodeState {
    #[inline]
unsafe fn from_glib(value: ffi::AstalWpNodeState) -> Self {
        skip_assert_initialized!();
        
match value {
            ffi::ASTAL_WP_NODE_STATE_ERROR => Self::Error,
            ffi::ASTAL_WP_NODE_STATE_CREATING => Self::Creating,
            ffi::ASTAL_WP_NODE_STATE_SUSPENDED => Self::Suspended,
            ffi::ASTAL_WP_NODE_STATE_IDLE => Self::Idle,
            ffi::ASTAL_WP_NODE_STATE_RUNNING => Self::Running,
            value => Self::__Unknown(value),
}
}
}

impl StaticType for NodeState {
                #[inline]
    #[doc(alias = "astal_wp_node_state_get_type")]
   fn static_type() -> glib::Type {
                    unsafe { from_glib(ffi::astal_wp_node_state_get_type()) }
                }
            }

impl glib::HasParamSpec for NodeState {
                type ParamSpec = glib::ParamSpecEnum;
                type SetValue = Self;
                type BuilderFn = fn(&str, Self) -> glib::ParamSpecEnumBuilder<Self>;
    
                fn param_spec_builder() -> Self::BuilderFn {
                    Self::ParamSpec::builder_with_default
                }
}

impl glib::value::ValueType for NodeState {
    type Type = Self;
}

unsafe impl<'a> glib::value::FromValue<'a> for NodeState {
    type Checker = glib::value::GenericValueTypeChecker<Self>;

    #[inline]
    unsafe fn from_value(value: &'a glib::Value) -> Self {
        skip_assert_initialized!();
        from_glib(glib::gobject_ffi::g_value_get_enum(value.to_glib_none().0))
    }
}

impl ToValue for NodeState {
    #[inline]
    fn to_value(&self) -> glib::Value {
        let mut value = glib::Value::for_value_type::<Self>();
        unsafe {
            glib::gobject_ffi::g_value_set_enum(value.to_glib_none_mut().0, self.into_glib());
        }
        value
    }

    #[inline]
    fn value_type(&self) -> glib::Type {
        Self::static_type()
    }
}

impl From<NodeState> for glib::Value {
    #[inline]
    fn from(v: NodeState) -> Self {
        skip_assert_initialized!();
        ToValue::to_value(&v)
    }
}

#[derive(Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
#[derive(Clone, Copy)]
#[non_exhaustive]
#[doc(alias = "AstalWpScale")]
pub enum Scale {
    #[doc(alias = "ASTAL_WP_SCALE_LINEAR")]
    Linear,
    #[doc(alias = "ASTAL_WP_SCALE_CUBIC")]
    Cubic,
#[doc(hidden)]
    __Unknown(i32),
}

#[doc(hidden)]
impl IntoGlib for Scale {
    type GlibType = ffi::AstalWpScale;

    #[inline]
fn into_glib(self) -> ffi::AstalWpScale {
match self {
            Self::Linear => ffi::ASTAL_WP_SCALE_LINEAR,
            Self::Cubic => ffi::ASTAL_WP_SCALE_CUBIC,
            Self::__Unknown(value) => value,
}
}
}

#[doc(hidden)]
impl FromGlib<ffi::AstalWpScale> for Scale {
    #[inline]
unsafe fn from_glib(value: ffi::AstalWpScale) -> Self {
        skip_assert_initialized!();
        
match value {
            ffi::ASTAL_WP_SCALE_LINEAR => Self::Linear,
            ffi::ASTAL_WP_SCALE_CUBIC => Self::Cubic,
            value => Self::__Unknown(value),
}
}
}

impl StaticType for Scale {
                #[inline]
    #[doc(alias = "astal_wp_scale_get_type")]
   fn static_type() -> glib::Type {
                    unsafe { from_glib(ffi::astal_wp_scale_get_type()) }
                }
            }

impl glib::HasParamSpec for Scale {
                type ParamSpec = glib::ParamSpecEnum;
                type SetValue = Self;
                type BuilderFn = fn(&str, Self) -> glib::ParamSpecEnumBuilder<Self>;
    
                fn param_spec_builder() -> Self::BuilderFn {
                    Self::ParamSpec::builder_with_default
                }
}

impl glib::value::ValueType for Scale {
    type Type = Self;
}

unsafe impl<'a> glib::value::FromValue<'a> for Scale {
    type Checker = glib::value::GenericValueTypeChecker<Self>;

    #[inline]
    unsafe fn from_value(value: &'a glib::Value) -> Self {
        skip_assert_initialized!();
        from_glib(glib::gobject_ffi::g_value_get_enum(value.to_glib_none().0))
    }
}

impl ToValue for Scale {
    #[inline]
    fn to_value(&self) -> glib::Value {
        let mut value = glib::Value::for_value_type::<Self>();
        unsafe {
            glib::gobject_ffi::g_value_set_enum(value.to_glib_none_mut().0, self.into_glib());
        }
        value
    }

    #[inline]
    fn value_type(&self) -> glib::Type {
        Self::static_type()
    }
}

impl From<Scale> for glib::Value {
    #[inline]
    fn from(v: Scale) -> Self {
        skip_assert_initialized!();
        ToValue::to_value(&v)
    }
}

