// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../../girs
// from ../../gtk-girs
// DO NOT EDIT

use crate::{ffi,Wp};
use glib::{translate::*};


#[doc(alias = "astal_wp_get_default")]
#[doc(alias = "get_default")]
#[allow(clippy::should_implement_trait)]pub fn default() -> Wp {
    assert_initialized_main_thread!();
    unsafe {
        from_glib_none(ffi::astal_wp_get_default())
    }
}
