// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../../girs
// from ../../gtk-girs
// DO NOT EDIT

use crate::{ffi,Available,Direction};
use glib::{prelude::*,translate::*};

glib::wrapper! {
    ///
    ///
    /// ## Properties
    ///
    ///
    /// #### `available`
    ///  the available state of this route
    ///
    /// Readable | Writeable | Construct Only
    ///
    ///
    /// #### `description`
    ///  Readable | Writeable | Construct Only
    ///
    ///
    /// #### `direction`
    ///  The direction for this route
    ///
    /// Readable | Writeable | Construct Only
    ///
    ///
    /// #### `index`
    ///  Readable | Writeable | Construct Only
    ///
    ///
    /// #### `name`
    ///  Readable | Writeable | Construct Only
    ///
    ///
    /// #### `priority`
    ///  Readable | Writeable | Construct Only
    #[doc(alias = "AstalWpRoute")]
    pub struct Route(Object<ffi::AstalWpRoute, ffi::AstalWpRouteClass>);

    match fn {
        type_ => || ffi::astal_wp_route_get_type(),
    }
}

impl Route {
            // rustdoc-stripper-ignore-next
            /// Creates a new builder-pattern struct instance to construct [`Route`] objects.
            ///
            /// This method returns an instance of [`RouteBuilder`](crate::builders::RouteBuilder) which can be used to create [`Route`] objects.
            pub fn builder() -> RouteBuilder {
                RouteBuilder::new()
            }
        

    #[doc(alias = "astal_wp_route_get_available")]
    #[doc(alias = "get_available")]
    pub fn available(&self) -> Available {
        unsafe {
            from_glib(ffi::astal_wp_route_get_available(self.to_glib_none().0))
        }
    }

    #[doc(alias = "astal_wp_route_get_description")]
    #[doc(alias = "get_description")]
    pub fn description(&self) -> glib::GString {
        unsafe {
            from_glib_none(ffi::astal_wp_route_get_description(self.to_glib_none().0))
        }
    }

    #[doc(alias = "astal_wp_route_get_device")]
    #[doc(alias = "get_device")]
    pub fn device(&self) -> i32 {
        unsafe {
            ffi::astal_wp_route_get_device(self.to_glib_none().0)
        }
    }

    #[doc(alias = "astal_wp_route_get_direction")]
    #[doc(alias = "get_direction")]
    pub fn direction(&self) -> Direction {
        unsafe {
            from_glib(ffi::astal_wp_route_get_direction(self.to_glib_none().0))
        }
    }

    #[doc(alias = "astal_wp_route_get_index")]
    #[doc(alias = "get_index")]
    pub fn index(&self) -> i32 {
        unsafe {
            ffi::astal_wp_route_get_index(self.to_glib_none().0)
        }
    }

    #[doc(alias = "astal_wp_route_get_name")]
    #[doc(alias = "get_name")]
    pub fn name(&self) -> glib::GString {
        unsafe {
            from_glib_none(ffi::astal_wp_route_get_name(self.to_glib_none().0))
        }
    }

    #[doc(alias = "astal_wp_route_get_priority")]
    #[doc(alias = "get_priority")]
    pub fn priority(&self) -> i32 {
        unsafe {
            ffi::astal_wp_route_get_priority(self.to_glib_none().0)
        }
    }
}

impl std::fmt::Display for Route {
    #[inline]
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        f.write_str(&self.name())
    }
}

// rustdoc-stripper-ignore-next
        /// A [builder-pattern] type to construct [`Route`] objects.
        ///
        /// [builder-pattern]: https://doc.rust-lang.org/1.0.0/style/ownership/builders.html
#[must_use = "The builder must be built to be used"]
pub struct RouteBuilder {
            builder: glib::object::ObjectBuilder<'static, Route>,
        }

        impl RouteBuilder {
        fn new() -> Self {
            Self { builder: glib::object::Object::builder() }
        }

                            /// the available state of this route
                            pub fn available(self, available: Available) -> Self {
                            Self { builder: self.builder.property("available", available), }
                        }

                            pub fn description(self, description: impl Into<glib::GString>) -> Self {
                            Self { builder: self.builder.property("description", description.into()), }
                        }

                            /// The direction for this route
                            pub fn direction(self, direction: Direction) -> Self {
                            Self { builder: self.builder.property("direction", direction), }
                        }

                            pub fn index(self, index: i32) -> Self {
                            Self { builder: self.builder.property("index", index), }
                        }

                            pub fn name(self, name: impl Into<glib::GString>) -> Self {
                            Self { builder: self.builder.property("name", name.into()), }
                        }

                            pub fn priority(self, priority: i32) -> Self {
                            Self { builder: self.builder.property("priority", priority), }
                        }

    // rustdoc-stripper-ignore-next
    /// Build the [`Route`].
    #[must_use = "Building the object from the builder is usually expensive and is not expected to have side effects"]
    pub fn build(self) -> Route {
assert_initialized_main_thread!();
    self.builder.build() }
}
