// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../../girs
// from ../../gtk-girs
// DO NOT EDIT

use crate::{ffi,Endpoint,MediaCategory,MediaRole,Node,Wp};
use glib::{prelude::*,signal::{connect_raw, SignalHandlerId},translate::*};
use std::{boxed::Box as Box_};

glib::wrapper! {
    ///
    ///
    /// ## Properties
    ///
    ///
    /// #### `media-category`
    ///  the media category of this stream.
    ///
    /// Readable
    ///
    ///
    /// #### `media-role`
    ///  the media role of this stream.
    ///
    /// Readable
    ///
    ///
    /// #### `target-endpoint`
    ///  Readable | Writeable
    ///
    ///
    /// #### `target-serial`
    ///  Readable | Writeable
    /// <details><summary><h4>Node</h4></summary>
    ///
    ///
    /// #### `channels`
    ///  A list of per channel volumes
    ///
    /// Readable
    ///
    ///
    /// #### `description`
    ///  The description of this node
    ///
    /// Readable
    ///
    ///
    /// #### `icon`
    ///  The icon of this node. Note that nodes do not have icons associated with them in
    /// pipewire, so the icon of the associated device is used instead.
    ///
    /// Readable | Writeable | Construct Only
    ///
    ///
    /// #### `id`
    ///  The pipewire id of this node.
    ///
    /// Readable
    ///
    ///
    /// #### `lock-channels`
    ///  Whether to lock the channels together or not.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `media-class`
    ///  The media class of this node
    ///
    /// Readable
    ///
    ///
    /// #### `mute`
    ///  The mute state of this node
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `name`
    ///  The name of this node
    ///
    /// Readable
    ///
    ///
    /// #### `path`
    ///  The object path of this node
    ///
    /// Readable
    ///
    ///
    /// #### `serial`
    ///  The object serial of this node.
    ///
    /// Readable
    ///
    ///
    /// #### `state`
    ///  the current state of this node.
    ///
    /// Readable
    ///
    ///
    /// #### `volume`
    ///  The volume of this node
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `volume-icon`
    ///  The volume icon of this node
    ///
    /// Readable
    ///
    ///
    /// #### `wp`
    ///  Readable | Writeable | Construct Only
    /// </details>
    ///
    /// # Implements
    ///
    /// [`NodeExt`][trait@crate::prelude::NodeExt]
    #[doc(alias = "AstalWpStream")]
    pub struct Stream(Object<ffi::AstalWpStream, ffi::AstalWpStreamClass>) @extends Node;

    match fn {
        type_ => || ffi::astal_wp_stream_get_type(),
    }
}

impl Stream {
            // rustdoc-stripper-ignore-next
            /// Creates a new builder-pattern struct instance to construct [`Stream`] objects.
            ///
            /// This method returns an instance of [`StreamBuilder`](crate::builders::StreamBuilder) which can be used to create [`Stream`] objects.
            pub fn builder() -> StreamBuilder {
                StreamBuilder::new()
            }
        

    #[doc(alias = "astal_wp_stream_get_media_category")]
    #[doc(alias = "get_media_category")]
    #[doc(alias = "media-category")]
    pub fn media_category(&self) -> MediaCategory {
        unsafe {
            from_glib(ffi::astal_wp_stream_get_media_category(self.to_glib_none().0))
        }
    }

    #[doc(alias = "astal_wp_stream_get_media_role")]
    #[doc(alias = "get_media_role")]
    #[doc(alias = "media-role")]
    pub fn media_role(&self) -> MediaRole {
        unsafe {
            from_glib(ffi::astal_wp_stream_get_media_role(self.to_glib_none().0))
        }
    }

    /// get the target [`Endpoint`][crate::Endpoint]
    #[doc(alias = "astal_wp_stream_get_target_endpoint")]
    #[doc(alias = "get_target_endpoint")]
    #[doc(alias = "target-endpoint")]
    pub fn target_endpoint(&self) -> Option<Endpoint> {
        unsafe {
            from_glib_none(ffi::astal_wp_stream_get_target_endpoint(self.to_glib_none().0))
        }
    }

    #[doc(alias = "astal_wp_stream_get_target_serial")]
    #[doc(alias = "get_target_serial")]
    #[doc(alias = "target-serial")]
    pub fn target_serial(&self) -> i32 {
        unsafe {
            ffi::astal_wp_stream_get_target_serial(self.to_glib_none().0)
        }
    }

    /// set the target [`Endpoint`][crate::Endpoint]
    #[doc(alias = "astal_wp_stream_set_target_endpoint")]
    #[doc(alias = "target-endpoint")]
    pub fn set_target_endpoint(&self, target: Option<&Endpoint>) {
        unsafe {
            ffi::astal_wp_stream_set_target_endpoint(self.to_glib_none().0, target.to_glib_none().0);
        }
    }

    #[doc(alias = "astal_wp_stream_set_target_serial")]
    #[doc(alias = "target-serial")]
    pub fn set_target_serial(&self, serial: i32) {
        unsafe {
            ffi::astal_wp_stream_set_target_serial(self.to_glib_none().0, serial);
        }
    }

    #[doc(alias = "media-category")]
    pub fn connect_media_category_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_media_category_trampoline<F: Fn(&Stream) + 'static>(this: *mut ffi::AstalWpStream, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(&from_glib_borrow(this))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::media-category".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_media_category_trampoline::<F> as *const ())), Box_::into_raw(f))
        }
    }

    #[doc(alias = "media-role")]
    pub fn connect_media_role_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_media_role_trampoline<F: Fn(&Stream) + 'static>(this: *mut ffi::AstalWpStream, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(&from_glib_borrow(this))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::media-role".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_media_role_trampoline::<F> as *const ())), Box_::into_raw(f))
        }
    }

    #[doc(alias = "target-endpoint")]
    pub fn connect_target_endpoint_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_target_endpoint_trampoline<F: Fn(&Stream) + 'static>(this: *mut ffi::AstalWpStream, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(&from_glib_borrow(this))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::target-endpoint".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_target_endpoint_trampoline::<F> as *const ())), Box_::into_raw(f))
        }
    }

    #[doc(alias = "target-serial")]
    pub fn connect_target_serial_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_target_serial_trampoline<F: Fn(&Stream) + 'static>(this: *mut ffi::AstalWpStream, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(&from_glib_borrow(this))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::target-serial".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_target_serial_trampoline::<F> as *const ())), Box_::into_raw(f))
        }
    }
}

// rustdoc-stripper-ignore-next
        /// A [builder-pattern] type to construct [`Stream`] objects.
        ///
        /// [builder-pattern]: https://doc.rust-lang.org/1.0.0/style/ownership/builders.html
#[must_use = "The builder must be built to be used"]
pub struct StreamBuilder {
            builder: glib::object::ObjectBuilder<'static, Stream>,
        }

        impl StreamBuilder {
        fn new() -> Self {
            Self { builder: glib::object::Object::builder() }
        }

                            pub fn target_endpoint(self, target_endpoint: &Endpoint) -> Self {
                            Self { builder: self.builder.property("target-endpoint", target_endpoint.clone()), }
                        }

                            pub fn target_serial(self, target_serial: i32) -> Self {
                            Self { builder: self.builder.property("target-serial", target_serial), }
                        }

                            /// The icon of this node. Note that nodes do not have icons associated with them in
                            /// pipewire, so the icon of the associated device is used instead.
                            pub fn icon(self, icon: impl Into<glib::GString>) -> Self {
                            Self { builder: self.builder.property("icon", icon.into()), }
                        }

                            /// Whether to lock the channels together or not.
                            pub fn lock_channels(self, lock_channels: bool) -> Self {
                            Self { builder: self.builder.property("lock-channels", lock_channels), }
                        }

                            /// The mute state of this node
                            pub fn mute(self, mute: bool) -> Self {
                            Self { builder: self.builder.property("mute", mute), }
                        }

                            /// The volume of this node
                            pub fn volume(self, volume: f64) -> Self {
                            Self { builder: self.builder.property("volume", volume), }
                        }

                            pub fn wp(self, wp: &Wp) -> Self {
                            Self { builder: self.builder.property("wp", wp.clone()), }
                        }

    // rustdoc-stripper-ignore-next
    /// Build the [`Stream`].
    #[must_use = "Building the object from the builder is usually expensive and is not expected to have side effects"]
    pub fn build(self) -> Stream {
assert_initialized_main_thread!();
    self.builder.build() }
}
