// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../../girs
// from ../../gtk-girs
// DO NOT EDIT

use crate::ffi;
use glib::{prelude::*, translate::*};

//#[doc(alias = "astal_greet_login")]
//pub fn login(username: &str, password: &str, cmd: &str, _callback_: AsyncReadyCallback) {
//    unsafe { TODO: call ffi:astal_greet_login() }
//}

//#[doc(alias = "astal_greet_login_with_env")]
//pub fn login_with_env(username: &str, password: &str, cmd: &str, env: &[&str], _callback_: AsyncReadyCallback) {
//    unsafe { TODO: call ffi:astal_greet_login_with_env() }
//}
