// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../../girs
// from ../../gtk-girs
// DO NOT EDIT

use crate::{ffi,Response};

glib::wrapper! {
    /// Indicates that the request succeeded.
    ///
    /// # Implements
    ///
    /// [`ResponseExt`][trait@crate::prelude::ResponseExt]
    #[doc(alias = "AstalGreetSuccess")]
    pub struct Success(Object<ffi::AstalGreetSuccess, ffi::AstalGreetSuccessClass>) @extends Response;

    match fn {
        type_ => || ffi::astal_greet_success_get_type(),
    }
}

impl Success {
        pub const NONE: Option<&'static Success> = None;
    
}
