[options]
girs_directories = ["../../gtk-girs", "../../girs"]
library = "AstalNiri"
version = "0.1"
min_cfg_version = "0.1"
target_path = "."
work_mode = "normal"
use_gi_docgen = true
generate_safety_asserts = true
deprecate_by_min_version = true
single_version_file = true
generate_builder = true
trust_return_value_nullability = true

generate = [
    "AstalNiri.WorkspaceReferenceArgTag",
    "AstalNiri.ColumnDisplayTag",
    "AstalNiri.SizeChangeTag",
    "AstalNiri.LayoutSwitchTargetTag",
    "AstalNiri.Workspace",
    "AstalNiri.Window",
    "AstalNiri.Output",
    "AstalNiri.Niri",
    "AstalNiri.Overview",
    "AstalNiri.WindowLayout",
    "AstalNiri.PhysicalSize",
    "AstalNiri.Mode",
    "AstalNiri.LogicalOutput",
    "AstalNiri.msg",
]

manual = ["Gio.AsyncReadyCallback", "Gio.AsyncResult", "Json.Array"]

[[object]]
name = "AstalNiri.*"
status = "generate"
