// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../../girs
// from ../../gtk-girs
// DO NOT EDIT

use crate::{ffi};
use glib::{translate::*};

glib::wrapper! {
    #[derive(Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
    pub struct Geometry(Boxed<ffi::AstalRiverGeometry>);

    match fn {
        copy => |ptr| ffi::astal_river_geometry_copy(mut_override(ptr)),
        free => |ptr| ffi::astal_river_geometry_free(ptr),
        type_ => || ffi::astal_river_geometry_get_type(),
    }
}

impl Geometry {
    #[doc(alias = "astal_river_geometry_new")]
    pub fn new(x: u32, y: u32, width: u32, height: u32) -> Geometry {
        assert_initialized_main_thread!();
        unsafe {
            from_glib_full(ffi::astal_river_geometry_new(x, y, width, height))
        }
    }

    #[doc(alias = "astal_river_geometry_new_zero")]
    pub fn new_zero() -> Geometry {
        assert_initialized_main_thread!();
        unsafe {
            from_glib_full(ffi::astal_river_geometry_new_zero())
        }
    }
}
