// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../../girs
// from ../../gtk-girs
// DO NOT EDIT

use crate::{Score, ffi};
use glib::{
    prelude::*,
    signal::{SignalHandlerId, connect_raw},
    translate::*,
};
use std::boxed::Box as Box_;

glib::wrapper! {
    /// Object representing an applications .desktop file.
    ///
    /// ## Properties
    ///
    ///
    /// #### `app`
    ///  The underlying DesktopAppInfo.
    ///
    /// Readable | Writeable | Construct
    ///
    ///
    /// #### `frequency`
    ///  The number of times [`ApplicationExt::launch()`][crate::prelude::ApplicationExt::launch()] was called on this Application.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `name`
    ///  The name of this Application.
    ///
    /// Readable
    ///
    ///
    /// #### `entry`
    ///  Name of the .desktop of this Application.
    ///
    /// Readable
    ///
    ///
    /// #### `description`
    ///  Description of this Application.
    ///
    /// Readable
    ///
    ///
    /// #### `wm-class`
    ///  `StartupWMClass` field from the desktop file. This represents the `WM_CLASS` property of the main window of the application.
    ///
    /// Readable
    ///
    ///
    /// #### `executable`
    ///  `Exec` field from the desktop file. Note that if you want to launch this Application you should use the [method@
    /// AstalApps.Application.launch] method.
    ///
    /// Readable
    ///
    ///
    /// #### `icon-name`
    ///  `Icon` field from the desktop file. This is usually a named icon or a path to a file.
    ///
    /// Readable
    ///
    ///
    /// #### `keywords`
    ///  `Keywords` field from the desktop file.
    ///
    /// Readable
    ///
    ///
    /// #### `categories`
    ///  `Categories` field from the desktop file.
    ///
    /// Readable
    ///
    /// # Implements
    ///
    /// [`ApplicationExt`][trait@crate::prelude::ApplicationExt]
    #[doc(alias = "AstalAppsApplication")]
    pub struct Application(Object<ffi::AstalAppsApplication, ffi::AstalAppsApplicationClass>);

    match fn {
        type_ => || ffi::astal_apps_application_get_type(),
    }
}

impl Application {
    pub const NONE: Option<&'static Application> = None;

    // rustdoc-stripper-ignore-next
    /// Creates a new builder-pattern struct instance to construct [`Application`] objects.
    ///
    /// This method returns an instance of [`ApplicationBuilder`](crate::builders::ApplicationBuilder) which can be used to create [`Application`] objects.
    pub fn builder() -> ApplicationBuilder {
        ApplicationBuilder::new()
    }
}

impl std::fmt::Display for Application {
    #[inline]
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        f.write_str(&ApplicationExt::name(self))
    }
}

// rustdoc-stripper-ignore-next
/// A [builder-pattern] type to construct [`Application`] objects.
///
/// [builder-pattern]: https://doc.rust-lang.org/1.0.0/style/ownership/builders.html
#[must_use = "The builder must be built to be used"]
pub struct ApplicationBuilder {
    builder: glib::object::ObjectBuilder<'static, Application>,
}

impl ApplicationBuilder {
    fn new() -> Self {
        Self {
            builder: glib::object::Object::builder(),
        }
    }

    /// The underlying DesktopAppInfo.
    pub fn app(self, app: &gio::DesktopAppInfo) -> Self {
        Self {
            builder: self.builder.property("app", app.clone()),
        }
    }

    /// The number of times [`ApplicationExt::launch()`][crate::prelude::ApplicationExt::launch()] was called on this Application.
    pub fn frequency(self, frequency: i32) -> Self {
        Self {
            builder: self.builder.property("frequency", frequency),
        }
    }

    // rustdoc-stripper-ignore-next
    /// Build the [`Application`].
    #[must_use = "Building the object from the builder is usually expensive and is not expected to have side effects"]
    pub fn build(self) -> Application {
        assert_initialized_main_thread!();
        self.builder.build()
    }
}

/// Trait containing all [`struct@Application`] methods.
///
/// # Implementors
///
/// [`Application`][struct@crate::Application]
pub trait ApplicationExt: IsA<Application> + 'static {
    /// Get a value from the .desktop file by its key.
    #[doc(alias = "astal_apps_application_get_key")]
    #[doc(alias = "get_key")]
    fn key(&self, key: &str) -> glib::GString {
        unsafe {
            from_glib_full(ffi::astal_apps_application_get_key(
                self.as_ref().to_glib_none().0,
                key.to_glib_none().0,
            ))
        }
    }

    /// Launches this application. The launched application inherits the environment of the launching process
    #[doc(alias = "astal_apps_application_launch")]
    fn launch(&self) -> bool {
        unsafe {
            from_glib(ffi::astal_apps_application_launch(
                self.as_ref().to_glib_none().0,
            ))
        }
    }

    /// Calculate a score for an application using fuzzy matching algorithm.
    ///
    /// # Returns
    ///
    #[doc(alias = "astal_apps_application_fuzzy_match")]
    fn fuzzy_match(&self, term: &str) -> Score {
        unsafe {
            let mut result = Score::uninitialized();
            ffi::astal_apps_application_fuzzy_match(
                self.as_ref().to_glib_none().0,
                term.to_glib_none().0,
                result.to_glib_none_mut().0,
            );
            result
        }
    }

    /// Calculate a score using exact string algorithm.
    ///
    /// # Returns
    ///
    #[doc(alias = "astal_apps_application_exact_match")]
    fn exact_match(&self, term: &str) -> Score {
        unsafe {
            let mut result = Score::uninitialized();
            ffi::astal_apps_application_exact_match(
                self.as_ref().to_glib_none().0,
                term.to_glib_none().0,
                result.to_glib_none_mut().0,
            );
            result
        }
    }

    #[doc(alias = "astal_apps_application_get_app")]
    #[doc(alias = "get_app")]
    fn app(&self) -> gio::DesktopAppInfo {
        unsafe {
            from_glib_none(ffi::astal_apps_application_get_app(
                self.as_ref().to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "astal_apps_application_set_app")]
    fn set_app(&self, value: &gio::DesktopAppInfo) {
        unsafe {
            ffi::astal_apps_application_set_app(
                self.as_ref().to_glib_none().0,
                value.to_glib_none().0,
            );
        }
    }

    #[doc(alias = "astal_apps_application_get_frequency")]
    #[doc(alias = "get_frequency")]
    fn frequency(&self) -> i32 {
        unsafe { ffi::astal_apps_application_get_frequency(self.as_ref().to_glib_none().0) }
    }

    #[doc(alias = "astal_apps_application_set_frequency")]
    fn set_frequency(&self, value: i32) {
        unsafe {
            ffi::astal_apps_application_set_frequency(self.as_ref().to_glib_none().0, value);
        }
    }

    #[doc(alias = "astal_apps_application_get_name")]
    #[doc(alias = "get_name")]
    fn name(&self) -> glib::GString {
        unsafe {
            from_glib_none(ffi::astal_apps_application_get_name(
                self.as_ref().to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "astal_apps_application_get_entry")]
    #[doc(alias = "get_entry")]
    fn entry(&self) -> glib::GString {
        unsafe {
            from_glib_none(ffi::astal_apps_application_get_entry(
                self.as_ref().to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "astal_apps_application_get_description")]
    #[doc(alias = "get_description")]
    fn description(&self) -> glib::GString {
        unsafe {
            from_glib_none(ffi::astal_apps_application_get_description(
                self.as_ref().to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "astal_apps_application_get_wm_class")]
    #[doc(alias = "get_wm_class")]
    fn wm_class(&self) -> glib::GString {
        unsafe {
            from_glib_none(ffi::astal_apps_application_get_wm_class(
                self.as_ref().to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "astal_apps_application_get_executable")]
    #[doc(alias = "get_executable")]
    fn executable(&self) -> glib::GString {
        unsafe {
            from_glib_full(ffi::astal_apps_application_get_executable(
                self.as_ref().to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "astal_apps_application_get_icon_name")]
    #[doc(alias = "get_icon_name")]
    fn icon_name(&self) -> glib::GString {
        unsafe {
            from_glib_full(ffi::astal_apps_application_get_icon_name(
                self.as_ref().to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "astal_apps_application_get_keywords")]
    #[doc(alias = "get_keywords")]
    fn keywords(&self) -> Vec<glib::GString> {
        unsafe {
            let mut result_length1 = std::mem::MaybeUninit::uninit();
            let ret = FromGlibContainer::from_glib_full_num(
                ffi::astal_apps_application_get_keywords(
                    self.as_ref().to_glib_none().0,
                    result_length1.as_mut_ptr(),
                ),
                result_length1.assume_init() as _,
            );
            ret
        }
    }

    #[doc(alias = "astal_apps_application_get_categories")]
    #[doc(alias = "get_categories")]
    fn categories(&self) -> Vec<glib::GString> {
        unsafe {
            let mut result_length1 = std::mem::MaybeUninit::uninit();
            let ret = FromGlibContainer::from_glib_full_num(
                ffi::astal_apps_application_get_categories(
                    self.as_ref().to_glib_none().0,
                    result_length1.as_mut_ptr(),
                ),
                result_length1.assume_init() as _,
            );
            ret
        }
    }

    #[doc(alias = "app")]
    fn connect_app_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_app_trampoline<P: IsA<Application>, F: Fn(&P) + 'static>(
            this: *mut ffi::AstalAppsApplication,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(Application::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::app".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_app_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "frequency")]
    fn connect_frequency_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_frequency_trampoline<
            P: IsA<Application>,
            F: Fn(&P) + 'static,
        >(
            this: *mut ffi::AstalAppsApplication,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(Application::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::frequency".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_frequency_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "name")]
    fn connect_name_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_name_trampoline<P: IsA<Application>, F: Fn(&P) + 'static>(
            this: *mut ffi::AstalAppsApplication,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(Application::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::name".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_name_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "entry")]
    fn connect_entry_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_entry_trampoline<P: IsA<Application>, F: Fn(&P) + 'static>(
            this: *mut ffi::AstalAppsApplication,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(Application::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::entry".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_entry_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "description")]
    fn connect_description_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_description_trampoline<
            P: IsA<Application>,
            F: Fn(&P) + 'static,
        >(
            this: *mut ffi::AstalAppsApplication,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(Application::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::description".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_description_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "wm-class")]
    fn connect_wm_class_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_wm_class_trampoline<
            P: IsA<Application>,
            F: Fn(&P) + 'static,
        >(
            this: *mut ffi::AstalAppsApplication,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(Application::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::wm-class".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_wm_class_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "executable")]
    fn connect_executable_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_executable_trampoline<
            P: IsA<Application>,
            F: Fn(&P) + 'static,
        >(
            this: *mut ffi::AstalAppsApplication,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(Application::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::executable".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_executable_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "icon-name")]
    fn connect_icon_name_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_icon_name_trampoline<
            P: IsA<Application>,
            F: Fn(&P) + 'static,
        >(
            this: *mut ffi::AstalAppsApplication,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(Application::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::icon-name".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_icon_name_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "keywords")]
    fn connect_keywords_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_keywords_trampoline<
            P: IsA<Application>,
            F: Fn(&P) + 'static,
        >(
            this: *mut ffi::AstalAppsApplication,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(Application::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::keywords".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_keywords_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "categories")]
    fn connect_categories_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_categories_trampoline<
            P: IsA<Application>,
            F: Fn(&P) + 'static,
        >(
            this: *mut ffi::AstalAppsApplication,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(Application::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::categories".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_categories_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }
}

impl<O: IsA<Application>> ApplicationExt for O {}
