[options]
girs_directories = ["../../gtk-girs", "../../girs"]
library = "AstalBluetooth"
version = "0.1"
min_cfg_version = "0.1"
target_path = "."
work_mode = "normal"
use_gi_docgen = true
generate_safety_asserts = true
deprecate_by_min_version = true
single_version_file = true
generate_builder = true
trust_return_value_nullability = true

generate = [
    "AstalBluetooth.Adapter",
    "AstalBluetooth.Device",
    "AstalBluetooth.Bluetooth",
]

manual = [
    "GLib.Error",
    "Gio.AsyncReadyCallback",
    "Gio.AsyncResult",
    "GLib.ObjectPath",
]

[[object]]
name = "AstalBluetooth.*"
status = "generate"
