// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../../girs
// from ../../gtk-girs
// DO NOT EDIT

use crate::{ffi,Connectivity,DeviceState,Internet,Network,Primary,State};
use glib::{prelude::*,translate::*};


#[doc(alias = "astal_network_primary_to_string")]
pub fn primary_to_string(self) -> glib::GString {
    assert_initialized_main_thread!();
    unsafe {
        from_glib_full(ffi::astal_network_primary_to_string(self.into_glib()))
    }
}

#[doc(alias = "astal_network_primary_from_connection_type")]
pub fn primary_from_connection_type(type_: &str) -> Primary {
    assert_initialized_main_thread!();
    unsafe {
        from_glib(ffi::astal_network_primary_from_connection_type(type_.to_glib_none().0))
    }
}

#[doc(alias = "astal_network_state_to_string")]
pub fn state_to_string(self) -> glib::GString {
    assert_initialized_main_thread!();
    unsafe {
        from_glib_full(ffi::astal_network_state_to_string(self.into_glib()))
    }
}

#[doc(alias = "astal_network_connectivity_to_string")]
pub fn connectivity_to_string(self) -> glib::GString {
    assert_initialized_main_thread!();
    unsafe {
        from_glib_full(ffi::astal_network_connectivity_to_string(self.into_glib()))
    }
}

#[doc(alias = "astal_network_device_state_to_string")]
pub fn device_state_to_string(self) -> glib::GString {
    assert_initialized_main_thread!();
    unsafe {
        from_glib_full(ffi::astal_network_device_state_to_string(self.into_glib()))
    }
}

#[doc(alias = "astal_network_internet_from_device")]
pub fn internet_from_device(device: &impl IsA<nm::Device>) -> Internet {
    assert_initialized_main_thread!();
    unsafe {
        from_glib(ffi::astal_network_internet_from_device(device.as_ref().to_glib_none().0))
    }
}

#[doc(alias = "astal_network_internet_to_string")]
pub fn internet_to_string(self) -> glib::GString {
    assert_initialized_main_thread!();
    unsafe {
        from_glib_full(ffi::astal_network_internet_to_string(self.into_glib()))
    }
}

#[doc(alias = "astal_network_get_default")]
#[doc(alias = "get_default")]
#[allow(clippy::should_implement_trait)]pub fn default() -> Network {
    assert_initialized_main_thread!();
    unsafe {
        from_glib_full(ffi::astal_network_get_default())
    }
}
